### ISSUE TITLE
loot sheet limited to 3 PCs and other unexpected behavior

### ISSUE THREAD

**Issue by miromonti** [jopeek/fvtt-loot-sheet-npc-5e#101]
When I create a new loot sheet, only three of the game's five PCs show up under Permissions. When I click on Permissions to choose Owner or Observer, five dots appear on the Actors Directory next to the loot sheet, but the loot sheet says "Split 3 Ways". I can't seem to add the other two PCs or change the three listed in the loot sheet in any way.

Configuring Permissions via right-click on the loot sheet in the Actors Directory doesn't do any better. And if I Save Changes such that Permissions on the sheet differ from the Configuring Permissions, closing the loot sheet pops open the Configuring Permissions window as many as eleven times.

Any ideas why this is? And how to get all five PCs as expected?

**Comment by jopeek** [comment]
Do all five players have a character assigned to them? I’m guessing only three do.

**Comment by miromonti** [comment]
Good call — and correct! I didn't know that was important, but now I do. 

I wonder whether this fix also clears that odd behavior of multiple Configuring Permissions window popping open; we'll see.

**Comment by jopeek** [comment]
Check it in the players list in the bottom left, not the permissions. Make sure when you edit a player there, they have a character assigned.

**Comment by naesean** [comment]
Aha! I had no idea that configuration was there. Foundry VTT really needs to improve its documentation... Thanks!
