### ISSUE TITLE
Return (Enter) Button Triggers Loot All

### ISSUE THREAD

**Issue by kdmcdrm** [jopeek/fvtt-loot-sheet-npc-5e#103]
Hello, I'm curious if this is true for everyone, surprised no one else has brought it up. I'm finding that hitting enter triggers the Loot All button. Several of my players accidentally triggered it while trying to put coins into a shared inventory they use. They (and I) type the currency values in and hit enter... and then everything comes out.
Also (minor thing), +value and -value don't work in the currency fields. They work almost everywhere else in Foundry, so we expected them to.

Thanks!

**Comment by olavmueller** [comment]
Yes, this is a problem I am experiencing as well. Would be great if it could be fixed.

**Comment by olavmueller** [comment]
I created a pull request which should fix this. I hope jopeek gets a chance to review this soon.
