### ISSUE TITLE
Splitting currency button no longer working

### ISSUE THREAD

**Issue by Avitale34** [jopeek/fvtt-loot-sheet-npc-5e#115]
I am having trouble getting the split currency button in the bottom left to work. Everything looks normal but when I click it nothing happens.

**Comment by acrimony616** [comment]
Do you have the LibWrapper module? I had it and used Find the Culprit! and discovered that was causing the issue.

**Comment by alessiocali** [comment]
+1. I've been having this problem last night while playing. People over reddit seem to also have it:

https://www.reddit.com/r/FoundryVTT/comments/ln1dnf/distribute_gold_to_players/gnyb8dk?utm_source=share&utm_medium=web2x&context=3

**Comment by alessiocali** [comment]
Found the bug. The module uses the permission list set on the Actor to do a reverse lookup, and from the permission get each player and then its character. Problem is, if you have a set up like : "Default Permission: Owner; Per-Character Permission: Default" then the permission list doesn't contain the entries for each character, and hence nothing is done.

![image](https://user-images.githubusercontent.com/7502952/112749047-6f642f80-8fc8-11eb-89f5-ffc8ab27e21a.png)

In this test the red-lined player got all the coins, the others got nothing.

See lootsheetnpc5e.js at line 804 : actorData.permission is empty if permissions are set to default.

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blame/a83d72122ed9e154e37aeecb02de1569a92d4cb1/lootsheetnpc5e.js#L804

**Comment by alessiocali** [comment]
Workaround: set permissions to non-defaults, or clear them all, reload, then configure permissions from the loot sheet **exclusively**

**Comment by jopeek** [comment]
Fixed in 3.0.1. Thanks
