### ISSUE TITLE
[Suggestion] Be able to change different items from GP to SP or CP.

### ISSUE THREAD

**Issue by mrtrumaine** [jopeek/fvtt-loot-sheet-npc-5e#116]
Just wondering if you would be able to set it so not everything uses GP and we are able to have it setup for players to purchase with SP or CP.

**Comment by Streyder** [comment]
The players can buy using SP and CP. It is automatically converted into GP, than substracted and change given back to them.
CURRENTLY this is buggy but I made a pull request to fix it: https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/126

Please make sure you uncheck the "Convert currency after purchases?" setting.
