### ISSUE TITLE
Unable to set permissions

### ISSUE THREAD

**Issue by HarryWraith** [jopeek/fvtt-loot-sheet-npc-5e#117]
I find myself unable to set permission for players either at an Actor or Token level. i.e. master or instance. All players have been assigned an Actor. 

Edit: just to add, I've taken it right back to no modules except this one.

![image](https://user-images.githubusercontent.com/59278137/111482055-73bc5d00-872b-11eb-9b54-b60806900063.png)

**Comment by HarryWraith** [comment]
OK got it working after reading a reddit post. Others have been confused by the same thing. A request then is for you to make the **_i_** popout on permissions clearer and do a quick vid on it.

**Comment by Streyder** [comment]
From my perspective there is no need for a merchent ever to be editable by the players right? So maybe that option can just be removed?

**Comment by HarryWraith** [comment]
> From my perspective there is no need for a merchent ever to be editable by the players right? So maybe that option can just be removed?

Agree, but there may be some db code requirement that requires permission to be set. 

I did find out why it wasn't letting me asign; essentially it was because an actor was unassigned to a player. This needs to be explained better somewhere.

**Comment by Streyder** [comment]
I would suggest to just remove the setting all together. Set it to "editable" by all players if it is a loot box, set it to not editable for merchants.
That actually removes functionality but it is no loss imo and simplifies everything big time
