### ISSUE TITLE
[Feature Request] Collaboration tidy5e-sheet

### ISSUE THREAD

**Issue by justinthejaguar** [jopeek/fvtt-loot-sheet-npc-5e#118]
My players and I use your loot sheet npc5e module for all of my merchants, the party pack, and chests in dungeons. One of the grips I get from my players is that their sheets look completely different from the loot sheets. I was wondering if you and sdenec would want to work together on using some of the tidysheet features that have been a hit like expanding item cards from the sheet and the clean aesthetic.

I added a similar request to tidy5e-sheet.
https://github.com/sdenec/tidy5e-sheet/issues/279

**Comment by DanielBoettner** [comment]
Maybe we can ping  @sdenec about this?

I would be absolutely in favor of collaborating on this.
Tidy sheet is awesome looking.

Current version of the lootsheet however is already closer to the look of the tidy sheet at least.
