### ISSUE TITLE
Price modifier only x2, can't increase more

### ISSUE THREAD

**Issue by Saergaras** [jopeek/fvtt-loot-sheet-npc-5e#139]
This "issue" was fixed some month ago, but now it does'nt work anymore :( I'm playing Curse of Strahd, and would LOVE to be able to increase the price modifier to x10.

I think a bigger slider would be amazing for a lot of DM's :D

**Comment by Streyder** [comment]
Fixed in: https://github.com/jopeek/fvtt-loot-sheet-npc-5e/pull/142
