### ISSUE TITLE
Error when trying to use Better Roll Tables with Compendium entries

### ISSUE THREAD

**Issue by adougherty** [jopeek/fvtt-loot-sheet-npc-5e#140]
When trying to load a merchant's loot sheet from a roll table that references a roll table in a compendium the follow error triggers:

**Error:** Required field type not present in OwnedItem.
**Javascript Console Log:**

```
Error: Required field type not present in OwnedItem.
    at OwnedItem._validateRequiredField (opt/foundryvtt/dist/database/odm/abstract.js:1)
    at OwnedItem.validate (opt/foundryvtt/dist/database/odm/abstract.js:1)
    at Function._onCreate (opt/foundryvtt/dist/database/odm/embedded.js:1)
    at async Socket.handleEvent (opt/foundryvtt/dist/sockets.js:1)
_handleError @ foundry.js:3780
lootsheetnpc5e.js:455 Uncaught (in promise) Error: Required field type not present in OwnedItem.
    at OwnedItem._validateRequiredField (opt/foundryvtt/dist/database/odm/abstract.js:1)
    at OwnedItem.validate (opt/foundryvtt/dist/database/odm/abstract.js:1)
    at Function._onCreate (opt/foundryvtt/dist/database/odm/embedded.js:1)
    at async Socket.handleEvent (opt/foundryvtt/dist/sockets.js:1)
```

**Reproduce:**
1. Install Modules: Loot Sheet NPC 5e, Better Roll Tables
2. Create 2 compendiums "Rolltables," and "Items"
3. Create a test item "Test Item" and put it in the Items Compendium
4. Create a roll table "Table B"
5. Add 1 item: "Items Compendium" version of "Test Item" as only entry in Table B.
6. Better Table Type = "Default Table", Roll Table Formula = 1
7. put "Table B" into Rolltable Compendium
8. Create a roll table "Table A"
9. Add 1 item: "Rolltable Compendium" version of "Table B" as only entry in Table A
10. Better Table Type = "Default Table", Roll Table Formula = 1
11. Create a new Actor type "NPC" named "Merchant"
12. Change NPC sheet to dnd5e.LootSheet5eNPC
13. Change type of sheet to Merchant
14. Set Rollable Table to "Table A"
15. Better Table Type = "Better Table", Roll Table Formula = 1
15. Set Shop Quantity formula to 1
16. Click "Update Shop Inventory" this results in the above error "Required field type not present in OwnedItem."

**Use Cases**
1. If set up properly, this should have the Merchant look up Table A, which rolls to the 1st entry, which is a reference to "Table B" in the "Rolltable Compendium" Table B then rolls and results with the 1st item, which is a reference to "Test Item" in the "Items Compendium" which should be the final item returned to the Loot Sheet Merchant

2. There is an related error, if "Table B" refers to an item that has been loaded into the game (Not in compendium) in which it cannot find a specific item id._

In both of the above use cases, clicking on the "Roll+" button in "Table A" resolves everything correctly. The error only occurs when Loot Sheet is initiating the roll.

**Comment by Streyder** [comment]
I am also interessted in this. Hopefully I will have time to implement this within the next few weeks.
