### ISSUE TITLE
Selling items (mercahant)

### ISSUE THREAD

**Issue by Zarhog** [jopeek/fvtt-loot-sheet-npc-5e#144]
would it be possible to add the option for players to drag an item into the merchant loot sheet then have it prompt them with a do you wish to sell this item for X amount. 

then if yes it sells the items and quantity adding the item to the loot sheet inventory and removing the gold from the vender then adding it to the players active character. 

it would also be nice if you could toggle this as an option on the sheet, i.e. if its not toggled it dosnt work. 

Then it would also be nice if like the merchant section if there was a slider for price that it gives the player ranging between 0% and 100% of the items value. Please get back to me at Zarhog1@gmail.com

**Comment by Nedrapter** [comment]
I would totally want to see that too, with more emphasis on the price slider of selling, similar to the modifier on buying. A generous merchant would sell at 90% and buy at 100% while a stingy merchant would sell at 120% and buy at 80% for example!
