### ISSUE TITLE
Toggle Gm needed

### ISSUE THREAD

**Issue by Zarhog** [jopeek/fvtt-loot-sheet-npc-5e#145]
in order to use your sheets there needs to be a Gm on the map, can you please update this so it changes to 
GM
Trial Gm
Trusted 
NONE

as toggles in the settings please

**Comment by jocolamarco** [comment]
Yes, please, this would be great. It's currently a pain for some users that require the GM to do shopping.

**Comment by DanielBoettner** [comment]
The requirement for a GM in the scene is gone.
A GM still needs to be online.

Handling it via other user levels as well would entail a lot of work as far as I can think through the implications.

We would have to check for each user if they can actually update the specific actor.
Just to prevent errors.

On top of that the logic to check which user permission level is sufficient and which levels are higher than others.

It can/could all be done. But at least my view is.

* Part of the requested feature is now included
* low prio on the other part from my end
