### ISSUE TITLE
Module not working correctly on newest version of foundry

### ISSUE THREAD

**Issue by JoaoPaul54** [jopeek/fvtt-loot-sheet-npc-5e#146]
Almost certainly that you already know it but currently in foundry 0.8.x the module is not working correctly.
Buying from a merchant deletes all the money from the player (not the cost) and doesn't give the item.

**Comment by jopeek** [comment]
Yeah there is a branch with some fixes but it’s not finished yet.

**Comment by JoaoPaul54** [comment]
Awesome.

Don't take the following as me pressuring you please but, is there any ETA on it? Specially the merchants. Shameful to admit but I did not backed up my foundry and currently my town is merchantless :P

Just want to know if for my next session I will need to stay away from the town or not.

**Comment by jopeek** [comment]
Ah yikes! I may be able to have something working within the next week.

**Comment by JoaoPaul54** [comment]
hehe, no worries. my session is friday s ill just stay clear of otwn ;)

thanks

**Comment by jackkerouac** [comment]
If it helps, I get the following error when trying to convert an actor to a lootable actor:
`lootables.js:84 Uncaught (in promise) TypeError: game.users.entries.filter is not a function
    at LootablesApp.convertToLootable (lootables.js:84)
    at HTMLButtonElement.i (jquery.min.js:2)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)`

**Comment by RavenknightDM** [comment]
This and Sky's POI-sheet are the only reasons why I haven't taken the plunge to 0.8.6 yet. :D Can't play without lootsheet.

**Comment by jopeek** [comment]
Please give 3.1.0 a shot and report any new issues.
