### ISSUE TITLE
Roll tables in Lootsheet for the 1.8.6 version of Foundry

### ISSUE THREAD

**Issue by scottjfox1984** [jopeek/fvtt-loot-sheet-npc-5e#149]
I'm not sure if anyone has reported on this yet but I'm running into these issues in the console 

when i click to update inventory from a selected roll table I receive this

VM55667 lootsheetnpc5e.js:307 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at LootSheet5eNPC._merchantInventoryUpdate (VM55667 lootsheetnpc5e.js:307)
    at HTMLButtonElement.<anonymous> (VM55667 lootsheetnpc5e.js:194)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
_merchantInventoryUpdate @ VM55667 lootsheetnpc5e.js:307

thank you!

**Comment by jopeek** [comment]
The current lootsheet version isn’t fully compatible yet. I’m working on a release soon.

**Comment by scottjfox1984** [comment]
Thank you! You do some awesome work, I love the tool

Sent via the Samsung Galaxy Note20 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jopeek** [comment]
Please give 3.1.0 a shot and report any new issues.
