### ISSUE TITLE
Merchant option not working

### ISSUE THREAD

**Issue by simondw2000** [jopeek/fvtt-loot-sheet-npc-5e#150]
My players are unable to purchase items from merchants. There's no error message or anything, it simply does nothing.
I'm hoping I'm just doing something wrong. Can you help at all?

Steps...

GM
1. Create NPC
2. Change sheet settings to loot sheet.
3. Change type to merchant.
4. Grant players "Observer" permission (have also tried owner).
5. Add some items.
6. Drag token to VTT.

Player
1. Login and ensure that a character is assigned.
2. Double click merchant token to open sheet.
3. Click "Buy Item" button next to an item.
4. Nothing happens. (No Item transfer, no gold reduction)

I have had multiple players try buying things, and have logged in as a player myself to try it.
I have re-created the merchant several times, trying all different permissions settings.

**Comment by jopeek** [comment]
If you’re on FVTT 0.8.x, then this mod is not yet working properly there.

**Comment by simondw2000** [comment]
Aha I see. Thank you for replying. I'll wait for the next update then.
