### ISSUE TITLE
Items not stacking from Better Roll Tables

### ISSUE THREAD

**Issue by Wade0004** [jopeek/fvtt-loot-sheet-npc-5e#156]
Sorry, I'm unsure if this is a issue from BRT, or Loot Sheet, but it worked before 0.8.x and it's not working now.  
When adding multiple items from a BRT generated character the items no longer "stack." 
![Capture](https://user-images.githubusercontent.com/74107522/123293991-ad8ec380-d4d1-11eb-992f-b683f9e91751.PNG)

If I "roll" them into chat they do however "stack," and so I thought I'd report it here along with on the BRT github just in case.
![Capture2](https://user-images.githubusercontent.com/74107522/123294145-cf884600-d4d1-11eb-8d56-e81b213449b1.PNG)

Sorry, I don't know enough to pinpoint where the error is coming from but I LOVE how your modules interact to create loot stashes and stores for me on the fly.  Thank you so much for your work!

**Comment by DanielBoettner** [comment]
please recreate in brt repo, if not already done.

cleaning up the issues
