### ISSUE TITLE
Old versions of module require newer version of FoundryVTT

### ISSUE THREAD

**Issue by IamATaako** [jopeek/fvtt-loot-sheet-npc-5e#157]
I tried taking the manifest link from Foundry's website in order to use the 0.7.6 version of the module, but it is giving me an error saying it need a more modern version of Foundry to even install.

**Comment by jopeek** [comment]
You can’t use the manifest link, they all point to the latest version. You’d have to download an older version from the GitHub releases page and install it into the data modules folder manually to get an old version up and running.
