### ISSUE TITLE
Hide Actions tab from module "character-actions-list-5e"

### ISSUE THREAD

**Issue by jocolamarco** [jopeek/fvtt-loot-sheet-npc-5e#158]
Do not display actions tab in the loot sheet:

![image](https://user-images.githubusercontent.com/45291719/123627191-9c172580-d809-11eb-85a0-99ec34aafe86.png)

Should this be handled in this module or on the other one?

https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions

**Comment by jopeek** [comment]
Probably the other one… it could have a list of exemption sheet types or something.

**Comment by jocolamarco** [comment]
Do you think this is easy to add:

> Ah this is something the other module can (hopefully) opt out of:
> 
> If the blockActionsTab option in the Application is true, the actions tab will not auto-inject.
> 
> `app.options.blockActionsTab = true`

**Comment by jocolamarco** [comment]
Not an issue after I updated both and removed actions injection from NPC sheets
