### ISSUE TITLE
Make it clear that you can assign a roll table to both the "Merchant" AND "Loot" Actor settings

### ISSUE THREAD

**Issue by kalibos** [jopeek/fvtt-loot-sheet-npc-5e#161]
Only the "Merchant" option offers an option to select which rollable table you want the actor to use. "Loot" doesn't have it.

I found this incredibly confusing. I ended up contacting the developer of the Loot Populator module to ask him how I might assign different tables to different individual actors, and he was the one that told me that the functionality is built in to Loot Sheet NPC 5e, you just have to choose the table by first switching the actor to "Merchant", then switch it to "Loot".

Please either add the ability to pick tables directly from that screen, or make a note of this in the readme that this is possible. 

![loot sheet npc](https://user-images.githubusercontent.com/30272707/124071866-4014f280-d9fd-11eb-810a-822940f6aa67.png)

**Comment by jopeek** [comment]
Fair point. I’ll be making that visible on both sheet “types” in the next release.

**Comment by DanielBoettner** [comment]
Should be "fixed" in the latest version
