### ISSUE TITLE
Drag & Drop doesn't decrement items.

### ISSUE THREAD

**Issue by pesky-wobbit** [jopeek/fvtt-loot-sheet-npc-5e#165]
Loot all works fine, but dragging individual items doesn't update the source.

**Comment by MelvinMcSnatch** [comment]
Same here. Also using the Drag'N'Transfer module which is probably causing a problem between the two.

**Comment by DanielBoettner** [comment]
I think to take care of this would be a new feature.
Currently a won't fix from  my side.

But I'm open to discussion.
