### ISSUE TITLE
Split coin feature not working.

### ISSUE THREAD

**Issue by jayfiction99** [jopeek/fvtt-loot-sheet-npc-5e#170]
When I use the split coin feature in my foundry game I get the following error. 

lootsheetnpc5e.js:884 Uncaught TypeError: Cannot read property 'data' of undefined
    at LootSheet5eNPC._hackydistributeCoins (lootsheetnpc5e.js:884)
    at LootSheet5eNPC._distributeCoins (lootsheetnpc5e.js:824)
    at HTMLButtonElement.<anonymous> (lootsheetnpc5e.js:198)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

Otherwise, the module works great, just can't use this basic feature. Weirdly the issue is only in one of my servers, it works fine in another. I've disabled all modules, restarted the server, created a new loot npc. Nothing has worked. Any help is appreciated.

**Comment by Avitale34** [comment]
Same issue

**Comment by Puggers** [comment]
Same issue as well. Some further context for the error. I have 5 users(not actors). When I transfer control of the offending actor from User 1(not working) to Users 2-5, the distribution works again. Any new users I create also duplicate the error. I have also tried rebuilding the sheet for the offending actor from scratch and it renders the same results.
