### ISSUE TITLE
Option to disable "Buy a Stack"

### ISSUE THREAD

**Issue by Zarhog** [jopeek/fvtt-loot-sheet-npc-5e#173]
The buy a stack feature seems to cause more damage in my games than good things, could you please add an option to disable this button by hiding it.

**Comment by GameCrazed** [comment]
I second this request! Either a popup to confirm their decision, a window to specify how many from the stack they wish to purchase, or an option to hide that button entirely would be greatly appreciated. I've had to fix my click-happy players mistakes too many times lately -__-

**Comment by MelvinMcSnatch** [comment]
I wholeheartedly agree. This is just one of those things where a group of otherwise smart people can't seem to avoid the wrong button.
