### ISSUE TITLE
[FEATURE REQUEST] Add option to not send loot messages to chat

### ISSUE THREAD

**Issue by BronzeToad** [jopeek/fvtt-loot-sheet-npc-5e#176]
I'd love the option to disable the messages generated when my players are looting fallen NPCs. If they're clicking 'Split x Ways' (5 in my case), for a group of 10 goblins it gets out of hand in the chat pretty quickly.

![Screen Shot 2021-09-21 at 11 48 06 PM](https://user-images.githubusercontent.com/45736019/134285201-d0c0d358-3765-458d-9ccf-da2b6c61b402.png)

**Comment by DanielBoettner** [comment]
Reasonable request. 
Will have to think about a good solution.

A quick fix would just be a simple setting.

But maybe there also is a way to update older messages instead of creating new messages.
