### ISSUE TITLE
 Currencies appear to be experiencing a reference issue VTT

### ISSUE THREAD

**Issue by lautensack** [jopeek/fvtt-loot-sheet-npc-5e#182]
![Capture](https://user-images.githubusercontent.com/6908251/136705995-4a44b09c-e501-4f38-8860-b1146f035bb6.PNG)
The Labels for currency are showing up as "[object Object]" in the NPC Loot Sheet. 
I am currently running the 5E 1.5.2 system on FoundryVTT 0.8.8

**Comment by Cynicide** [comment]
See my post here: https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/180#issuecomment-938609980
