### ISSUE TITLE
Many Many errors when enabled while VTTA Beyond Importer is used

### ISSUE THREAD

**Issue by Norc** [jopeek/fvtt-loot-sheet-npc-5e#19]
When the Loot-sheet-npc module is enabled while the VTTA Beyond Importer module is used, the console is spammed with pages of the following error:

![image](https://user-images.githubusercontent.com/64667579/82133239-b03fc500-97b7-11ea-8aea-71618c670a31.png)

I get pages of this. Nothing special about the character, happens in every character I've tried, in both 0.5.6 and 0.5.7. VTTA 2.2.14 and Loot Sheet 1.3.6. Only these two mods were enabled at the time of import. If Loot sheet is not enabled at the time of import, no errors occur.

I've brought this up with the VTTA team also, thanks!

**Comment by jopeek** [comment]
Thanks for the report. Lootsheet hasn’t been updated to work beyond 0.5.5 yet. Once it is, those error should be gone :)

**Comment by jopeek** [comment]
Also, the latest version of Lootsheet is 1.6.2, so make sure you update it from the module browser. But even that one hasn’t been tested on 0.5.6 or 0.5.7 yet. I hope to have an update late next week.

**Comment by Norc** [comment]
Wow, that number isn't even close. Okay I'll fix it, but logged https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/20 in case that is something that you have some control over, thanks.

**Comment by Norc** [comment]
Actually, I can't reproduce this behavior in 1.6.2! So... problem solved? Thanks and good luck.
