### ISSUE TITLE
[Feature Request] System support SW5e

### ISSUE THREAD

**Issue by drummerking523** [jopeek/fvtt-loot-sheet-npc-5e#190]
I've been using your mod for DND 5e and I think it's great. I was wondering if you could make a version compatible for SW5e. SW5e is a system built off the DND5e system for Star Wars. Thanks!

**Comment by DanielBoettner** [comment]
For the next months I think this is not realistic.
But I don't know how different the data structure in the systems is.

Feel free to do some research or ask around in the community.
But I just doubt that we will have the time in the near future.

Next thing will be update for v9.

I have other features in mind that are prepared. But evenfor that no timeframe is clear to be honest.

**Comment by DanielBoettner** [comment]
FYI I talked to the developer of the merchant sheet module.
And maybe we find a way to get this done at some point.

**Comment by TogaParty** [comment]
Commenting to watch this thread.  +1 on the request.
