### ISSUE TITLE
Loot Sheet Not working 

### ISSUE THREAD

**Issue by eeldridge10** [jopeek/fvtt-loot-sheet-npc-5e#193]
I have the most current version of Foundry, the most current version of Loot Sheet NPC 5e, and the most current version of DND5E. 

I've never used this module before and am kind of new to Foundry Moudles, but it's the only one i've had any issues with thus far. When I create a new NPC actor and change it's sheet type to Loot Sheet NPC, i loose any and all ability to interact with that actor. I can no longer click on its token or its name in a folder to bring up its sheet.  The console log shows something like this. I'm very confused and sad. Any help is appreciated. 
![image](https://user-images.githubusercontent.com/93287332/139134322-510da54d-fed4-4be3-ac6c-644a59a8baef.png)

**Comment by Kirin92** [comment]
Well... I hope it's fixed until Monday. I want my bag of holding back xD

**Comment by Avitale34** [comment]
Still having issues with loot sheet :( I can not drop any items on to it

**Comment by TenguGrib** [comment]
For mine the issue seems to be coming from coin values that I can't even see. The NPC will have nothing in any of the coin entries, but breaks when changed to a lootsheet. Changing all the values for coins to 1 allows the npc to change to a lootsheet without issue though.

**Comment by FGiorgi** [comment]
I have the same problem. This is the console log when I try to open a loot npc sheet:

TypeError: Object.values(...).map(...).sum is not a function
[Detected 1 package: lootsheetnpc5e]
    at LootSheet5eNPC.getData (lootsheetnpc5e.js:166)
    at async LootSheet5eNPC._render (foundry.js:2049)
    at async LootSheet5eNPC._render (foundry.js:2736)

Is there any chance this will be fixed by wednesday? I created a lot of loot actors for the upcoming dungeon and I have to recreate them all in a different way if this is not fixed ^^

**Comment by xanstin** [comment]
Just updated to latest 3.2.4. Still cant even open the sheet once I turn a new sheet into a loot sheet on token click or actor.

**Comment by fiagewinnt** [comment]
Just as a heads up for everybody having problem with this:
As soon as I unticked the option to include currency weight the sheets were working again.

![image](https://user-images.githubusercontent.com/61601634/144750030-0def2932-93b7-4966-8d8d-a80bc3947563.png)

**Comment by jopeek** [comment]
Thanks for the hint!

**Comment by DanielBoettner** [comment]
As far as I can tell this is fixed.
Please open another issue if you encounter a similar problem

**Comment by TenguGrib** [comment]
Awesome, I'll update and give it a try. I should be able to test it tomorrow or the day after.

**Comment by TenguGrib** [comment]
I've identified the issues we're coming from DFReds Pocket Change module. They update and I can no longer recreate the issue. Also, I love the new features you added!
