### ISSUE TITLE
Lootsheet breaking NPC sheet

### ISSUE THREAD

**Issue by TenguGrib** [jopeek/fvtt-loot-sheet-npc-5e#194]
![Screenshot 2021-11-07 213304](https://user-images.githubusercontent.com/93809766/140684785-f8f51e83-5817-448a-a45a-eb5d67ae06a3.jpg)

Occasionally, but  not reliably though, when an NPC sheet is changed into a lootsheet, the sheet breaks and becomes unusable. The token settings can still be accessed, but not the lootsheet. If it happens to a sheet with Linked data, the character sheet is destroyed.
I can reduce the frequency of the error by manually adjusting the coinage values, but my mass test still had it happen once.

**Comment by TenguGrib** [comment]
![Screenshot 2021-11-07 214027](https://user-images.githubusercontent.com/93809766/140685478-114b5d92-82b6-4b7c-a2b2-db8f3b41596b.jpg)

I managed to identify that when the NPC is killed, the money entries will occasionally read:
[object Object]

Sometimes having NAN added at the end, other times not, but when this happens, the sheet will break when converted. Manually fixing the values prevents breakage.

**Comment by DanielBoettner** [comment]
@TenguGrib If this is still happening, do you know which module generated the faulty currency entries?

The Lootsheet itself does not have automation to convert tokens to lootable.
With 3.3.81 an API was added that allows updating tokens to a lootable state,
but AFAIK nothing was in the module before that would do something like this.

**Comment by TenguGrib** [comment]
So my last session I noticed that the coinage occasionally breaks when the token dies. I would find one with [Object object] in each coin entry except any that has already contained an actual number, I'd fix them, replacing all the broken entries with 0's, then the token would die, and the coinage would be broken again. 
I'm busy with family for holidays, but I'll try and get a list of modules which might be contributing to the problem. CUB is for sure on the list though. 
I can bring the issue up on their pages too.
