### ISSUE TITLE
[Bug][Legacy] Currency Is Not Lootable 

### ISSUE THREAD

**Issue by Instg8r2000** [jopeek/fvtt-loot-sheet-npc-5e#195]
Players are unable to loot any currency displayed in the loot sheet. Neither the Loot All button nor Loot Coins button will transfer the currency.

**Comment by DanielBoettner** [comment]
Please test the latest version.

You can take a look at #222 , I attached a file of the latest unreleased version if by the time you read this
the release is not version 3.4.25 or higher.
