### ISSUE TITLE
Switching Between Loot/Merchant Not Working

### ISSUE THREAD

**Issue by pixelswirl** [jopeek/fvtt-loot-sheet-npc-5e#198]
foundry 0.8.9
dnd 1.5.5 (this was also happening in 1.5.3 before i updated)
I disabled all modules except Loot Sheet NPC and this is still happening

Sometimes switching back and forth between Loot & Merchant sheet types does not actually switch.  It can also differ between what I see and the players see.  (To me it looks like it's a merchant, my players see loot)  Also sometimes if I had a sheet as a Merchant, close foundry, and reopen it, it's now Loot. (On both my & the players' side)

**Comment by DanielBoettner** [comment]
I removed the code that handled the sheet update from the Lootsheet.
In the next release the sheet update will be handled by Foundry.
