### ISSUE TITLE
Lootsheet NPC Auto-update non-functional

### ISSUE THREAD

**Issue by Norc** [jopeek/fvtt-loot-sheet-npc-5e#20]
The latest version of LootSheet NPC 5E is 1.6.2, but the in-Foundry updater(version 0.5.7)  is not progressing me past 1.3.6:

![image](https://user-images.githubusercontent.com/64667579/82133859-9eadeb80-97be-11ea-9b18-fbc7370ae88c.png)

I'll uninstall and reinstall, but there might be something that needs fixing here.

**Comment by jopeek** [comment]
Nothing I can do there. I moved it from gitlab to GitHub so the update at that stage doesn’t work so it requires an uninstall and fresh install via the module browser. From then on the updates will work fine though.
