### ISSUE TITLE
Duplicate Entry at the end of split 

### ISSUE THREAD

**Issue by stgreenb** [jopeek/fvtt-loot-sheet-npc-5e#200]
Keep seeing an issue where one player tries to loot the sheets of some dead NPCs and when splitting 4 ways, an additional amount seems to pop up going to the player that did the split. Normally if this was a rounding amount, that would make sense, but here you can see its the total. 

Derpfeld-Guy receives: 3 gp coins, 2 sp coins
Sniper-John receives: 3 gp coins, 2 sp coins
Leonardo-Ken receives: 3 gp coins, 2 sp coins
Archibold-Patrick receives: 3 gp coins, 2 sp coins
Archibold-Patrick receives: 12 gp coins, 9 sp coins

**Comment by DanielBoettner** [comment]
Will try to reproduce.

A fix will likely only ship with the next update to get compatibility with Foundry >= v0.9
