### ISSUE TITLE
Unable to Update to Latest Version on Foundry v 0.8.9

### ISSUE THREAD

**Issue by justinthejaguar** [jopeek/fvtt-loot-sheet-npc-5e#206]
**Describe the bug**
![Screen Shot 2021-12-21 at 6 02 09 PM](https://user-images.githubusercontent.com/38022481/147008700-e1b794aa-7ec1-4c71-bc71-b96c40ab42d1.png)

**To Reproduce**
1. Update all in Add-on modules.
2. Above error pops.
3. Result screen: 
![Screen Shot 2021-12-21 at 5 59 43 PM](https://user-images.githubusercontent.com/38022481/147008822-15d437e8-1418-4172-ab1a-971c75577660.png)

**Expected behavior**
Update to latest version available or provide an error that the module is not compatible and the user must update to v9 Foundry if applicable.

**Desktop (please complete the following information):**
 - OS: node.js on raspberry pi
 - Browser Latest Chrome for M1 Mac Mini
 - Version Updating from 3.2.5 (Foundry is v 0.8.9)

**Additional context**

**Comment by jopeek** [comment]
Please try uninstalling and reinstalling.

**Comment by justinthejaguar** [comment]
Success.
