### ISSUE TITLE
The latest update throws an error while updating

### ISSUE THREAD

**Issue by tagnullde** [jopeek/fvtt-loot-sheet-npc-5e#208]
The latest update throws an error while updating:

![image](https://user-images.githubusercontent.com/44159008/147072257-f2617135-f969-49d8-b16b-5bcfd7b4bf1a.png)

**Comment by DanielBoettner** [comment]
We currently work on the release process after the refactor.
Thanks to your issue I looked into the module.json once more.

And it seems the module.json won't be updated properly currently.
I will look into it. And update the issue when solved.

**Comment by DanielBoettner** [comment]
This is fixed, but I will close this issue manually when I fixed another weird bug.

**Comment by DanielBoettner** [comment]
The latest release 3.3.81 should be installable via
* https://raw.githubusercontent.com/jopeek/fvtt-loot-sheet-npc-5e/master/module.json

But you can also wait. @jopeek will update the foundry listing later to point towards the updated master.
