### ISSUE TITLE
For 3.3.83, integration with monk's token bar is broken

### ISSUE THREAD

**Issue by robnmeyer** [jopeek/fvtt-loot-sheet-npc-5e#219]
**Describe the bug**
When using monk's token bar to convert to lootables, conversion seems to fail.  

**To Reproduce**
When using monk's token bar to convert to lootables, conversion seems to fail.  

1.  Highlight token and click "convert lootables" on the left side of the screen (from monk's token bar)
2. Notice that the sheet still look the same as a standard npc sheet even though the token looks like a lootable token.
3. Press 'revert lootable' from the top of the sheet.  All looks well.
4. Change the sheet manually to the lootsheet.
5. You cannot open the sheet any longer.

```

> TypeError: Cannot read properties of null (reading 'value')
> [Detected 1 package: lootsheetnpc5e]
>     at LootSheetNPC5eHelper.js:51
>     at Array.map (<anonymous>)
>     at Function.convertCurrencyFromObject (LootSheetNPC5eHelper.js:50)
>     at LootSheetNPC5e._prepareGMSettings (LootsheetNPC5e.js:789)
>     at LootSheetNPC5e.getData (LootsheetNPC5e.js:68)
>     at async LootSheetNPC5e._render (foundry.js:2049)
>     at async LootSheetNPC5e._render (foundry.js:2736)
> (anonymous) @ foundry.js:2013
> Promise.catch (async)
> render @ foundry.js:2011
> render @ foundry.js:3231
> EntitySheetConfig._updateObject @ monks-enhanced-journal.js:495
> await in EntitySheetConfig._updateObject (async)
> _onSubmit @ foundry.js:2825

```

**Comment by robnmeyer** [comment]
Running 0.8.9 Foundry, Monk's Token Bar 1.0.55 and Lootsheet NPC 5e 3.3.83

**Comment by DanielBoettner** [comment]
On first glance. I think this will be a won't fix.

The module now offers a direct [API ](https://github.com/DanielBoettner/fvtt-loot-sheet-npc-5e/wiki/Permissions)to convert a token to a lootableSheet.

With the module you can find a compendium with macros.
One macro for converting a single token.
A second macro to convert a selection of tokens.

The macros bascially do what the example in the wiki does.

I have to check if I already included a way to set the permissions to a specific type.
Default is "Observer" so players can loot.

If you think this is a good answer/solution. Please feel encouraged to create a issue for monks tokenbar.
I think for him to just do the API call with his module in the future. Would also be the easier way for him.

**Comment by robnmeyer** [comment]
Yes - if the Token Bar is reaching in and breaking any contract established, or any contract you wish to establish, then this bug should be assigned to that component.

**Comment by DanielBoettner** [comment]
I already created an issue in the repo to get ironmonk88's view on this.

For the user I recommend using the macros as long as the tokenbar support is broken.

**Comment by robnmeyer** [comment]
Yes - saw that.  Thanks.  I've disable that feature of Monks.  The macro(s) you've provided are great.
