### ISSUE TITLE
Shop clear inventory not working

### ISSUE THREAD

**Issue by Arternimus** [jopeek/fvtt-loot-sheet-npc-5e#227]
When updating a merchant loot sheet with clear inventory set to true it continues to just add items instead of clearing the inventory and then adding items.
Foundry V8.9
Lootsheet 3.4.1

**Comment by DanielBoettner** [comment]
Will try to reproduce that.

**Comment by DanielBoettner** [comment]
@Arternimus I left the version unchanged. But if you reinstall the latest version this should be fixed.

**Comment by Arternimus** [comment]
@DanielBoettner Its all working now and even with all the modules! Thank you for your lighting fast response time and all of the good work you guys put in. It is much appreciated!
