### ISSUE TITLE
Shop sheet weapon type issue

### ISSUE THREAD

**Issue by Arternimus** [jopeek/fvtt-loot-sheet-npc-5e#230]
You can not add weapons to the shop list that have the weapon type natural. Such as the dnd5e item Sprig of Mistletoe, Totem, ect.

Foundry Version 0.8.9
Loot Sheet Version 3.4.1
Game System DnD5e 1.5.6

**Comment by DanielBoettner** [comment]
Thanks for that.

I know the reason immediately. Will have to think about that.
Currently we filter them. So the sheet is clean from like a paw / tail / unarmed strike.

Will have to see if there is a better filter.
