### ISSUE TITLE
[bug] split gold and loot items not working

### ISSUE THREAD

**Issue by nirurin** [jopeek/fvtt-loot-sheet-npc-5e#231]
**Describe the bug**
Trying to use the auto 'split gold' function doesn't do anything. One player can loot the gold for themselves, but splitting doesn't work. 
Looting items doesn't work at all (neither by loot all or individually). 
Trying to populate a merchant using the roll tables doesn't do anything either. 

![Screenshot 2021-12-27 050504](https://user-images.githubusercontent.com/3751273/147436371-949091a7-a622-499b-bcf6-06efa6504e29.png)
This is the console for trying to restock a merchant. Seems to not throw an error, but the merchant inventory doesn't change (even if you have 'clear' ticked, it doesn't empty either, just stays as it was). 

![Screenshot 2021-12-27 050439](https://user-images.githubusercontent.com/3751273/147436372-c854162b-11db-424c-9e51-4431b97d6f77.png)
Error for trying to loot items. 

No errors or anything show up when doing the split, its like the console isn't see anything happening to report. 

Edit:
Tried using the 'dev' update version .25, but that seems to be exactly the same. No splitting gold, no looting items. If I try and purchase an item from a merchant, it says "no active character for this user" when I'm logged in as a user and their character is right there on the scene next to the merchant.

**Comment by DanielBoettner** [comment]
Yep, that was just really bad refactoring on my part 🙈 

I push a new version soon that should fix a number of issues when looting/buying and switching the sheet.

There where like 3-4 lootCoins methods in the code by the time of 3.3.x
