### ISSUE TITLE
Player can't open chest

### ISSUE THREAD

**Issue by FeelTheWay** [jopeek/fvtt-loot-sheet-npc-5e#233]
**Describe the bug**
Player can't open Chest with Loot Sheet NPC 5e
Player have control of its token
There is a NPC loot sheet in the map, all player have observer permission.
The player can't open the chest on click or double click. Nothing happens

**Expected behavior**
PLayer click on token chest and the windows pops up with items.

**Screenshots**
![image](https://user-images.githubusercontent.com/81187538/147737909-effffb34-ffbc-49cb-afa5-61722a86b9b1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave 
 - Version 1.33.106 Chromium: 96.0.4664.110 (Build officiel) (64 bits)

**Additional context**
FoundryVTT : 9.238
Dnd5E 1.5.6
Loot Shee NPC 5e 3.4.1

**Comment by DanielBoettner** [comment]
I think and hope my current dev branch will solve these issues.

However, we still did not test wit v9.
Il will update my dev foundry in the coming days so I can start checking for v9 functionallity.

In the meantime, could you check chromes/browsers dev console for error messages?

**Comment by FeelTheWay** [comment]
Client has no error in console on click or double click.
I don't know if the issue come from my parameters or not. But everything seems ok, triple check.

**Comment by FeelTheWay** [comment]
Some news. 

It's working now. I've understood why.
The "Individual permission is wierd. When I allow Player2 to loot, it unallow PLayer1 .
2+ players can't have the permission to open the chest ? Only 1 ?


Now the player with permission can open the Chest, loot money but can't loot items There is an error on clicking "Loot item"

"No active character for user"

![image](https://user-images.githubusercontent.com/81187538/147871578-ecf6e9d7-3d98-4a49-bc1f-e1e0ab62f187.png)

**Comment by DanielBoettner** [comment]
I suppose this is a test environment.

You will have to create a user for **Test** 

![image](https://user-images.githubusercontent.com/21986545/147873029-2295e8a1-f662-427b-8d4b-190a12e1f207.png)

And use a second browser or an incognito window.
![image](https://user-images.githubusercontent.com/21986545/147873087-f07d2cc7-18e3-45cc-b42e-569eed64fd3d.png)

Next update will bring optimization for permission handling again.

Issues with that should be clearer to fix for the GM in the future.

**Comment by FeelTheWay** [comment]
it's not a test environnement, it's a real user connected and well configured like your screenshot :)

He can loot money but not item.

**Comment by DanielBoettner** [comment]
I will test this again. The next update will have several bugfixes.
I let you know when release. The item looting should be fixed as well.

**Comment by DanielBoettner** [comment]
You can test https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.5.2 this pre release if you like.

**Comment by FeelTheWay** [comment]
Thanks, I'll try to install it before the end of week :)

**Comment by FeelTheWay** [comment]
An error when player click on chest

![image](https://user-images.githubusercontent.com/81187538/149080392-edb1545e-5df7-4ae8-9eb9-af0209c1de57.png)

I've bulk updated with Observer. She can double click on the chest but can't loot anything.

**Comment by FeelTheWay** [comment]
Another screenshot from my GM POV

Every player is set in "parametres/players configuration", I've already made a session with all of them and no problem to control their character.
Still only one is in Individual Permission section. I'm looking every where I don't see anything that explain missing ones.

![image](https://user-images.githubusercontent.com/81187538/149091625-829c8c2c-804b-4c2a-97ff-16c37d75771b.png)

**Comment by DanielBoettner** [comment]
Can you ping me on discord ?

I suspect a configuration issue. But we would have to test this.

**Comment by FeelTheWay** [comment]
Thank you. on FoundryDiscord ? what is your tag ? (FeelTheWay#8714)

**Comment by FeelTheWay** [comment]
Problems solved. (Configuration Issue + new module version)

Thank you very very much !

**Comment by SamF111** [comment]
@FeelTheWay what was the fix? I've got the same issue.

**Comment by DanielBoettner** [comment]
should be fixed
