### ISSUE TITLE
Loot Sheet Still not Working after upgrade to Foundry v9 

### ISSUE THREAD

**Issue by rtschaefer** [jopeek/fvtt-loot-sheet-npc-5e#237]
**Describe the bug**
(1) Players are unable to purchase from merchants, even though they have the Observer Permission set correctly.
(2) The avatars for 2 out of my 6 registered players do not even show up in Loot Sheet (only four avatars can be cycled/configured). 
(3) The new collapsing window makes it really cumbersome to update Merchant inventory, or to check player access status.

**To Reproduce**
Steps to reproduce the behavior (for bug Item #1 above):
1. Player and DM inside the area (store) with a merchant token stocked with items. Player's permission is set to Observer (eye icon).
2. Player attempts to buy something. 
3. Sometimes, a confirmation window appears, other times it does not. Either way.... 
4. Nothing at all happens. No sale. No exchange of currency. No purchased items sent to player inventory. 

**Expected behaviors**
(A) Players can buy items directly from a merchant as long as they have the currency in their inventory to do so. 
(B) All players are shown inside a loot sheet for the DM to cycle through permission (currently some players are missing)
(C) Configuration window does not collapse between each DM operation; DM does not have to constantly re-open a collapsed configuration window over and over again. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**
I absolutely love the Loot Sheet module. I can work around it no problem (players can just tell me what items they wish to purchase and I can complete the sale manually), but the lack of automation makes it less appealing to use.

**Comment by jopeek** [comment]
There still is no release that supports v9. It’s being worked on.

**Comment by rtschaefer** [comment]
> There still is no release that supports v9. It’s being worked on.

That's wonderful to hear!  I was thinking that the reason it stopped working for me was because I was still on 8.9 (I had the same problem then as well).  I look forward to the v9 release, and in the mean time, it is still extremely helpful and awesome to have NPCs as merchants with inventories!  :-)

**Comment by ctbritt** [comment]
> There still is no release that supports v9. It’s being worked on.

Do you have an eta on when v9 will be supported? I'm still getting the "No DM on scene" error...

**Comment by jopeek** [comment]
No eta, no. But soon-ish.

**Comment by DanielBoettner** [comment]
I updated my local dev to v9 now.
I will create a new branch for the current state of #234 
branch.

And update the PR with fixes for v9.
I hope that fixes for v9 are backwards compatible. 
We will se about that.

@ctbritt the "noactiveGM" should be gone in the next version.
We use the unique "uuid" to know which token is targeted in the future.
So GM can be on "scene for the session" while a player is buying stuff from a merchant in your start/landing page scene.

The new "welcome screen" (after install or update) will show a patchnotes tab that lists alot of the changes/features and buckfixes

**Comment by playest** [comment]
I'm trying to use this module but it apparently doesn"t work with v9. Do you know how I can use the current dev version in FVTT?

**Comment by jopeek** [comment]
V9 support is still being worked on.

**Comment by playest** [comment]
Can I help in any way? I know JS and web dev quite well but don't know anything about fvtt modules.

**Comment by DanielBoettner** [comment]
You can test https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.5.2 this pre release if you like.

In general most stuff is done.
I suppose its still a good day of work to get the populator settings working (currently the new "add filter rule" is not finished).

**Comment by ABrandau** [comment]
From a quick test I can see that the roll table population function is restored, i might be doing something wrong or the buy function is a bit wonky, when i buy something and finish its stock, the program deletes the item that is above it.

I am not completely sure if the buy item and buy stack work well, atleast they add the correct amounts to the player sheet but the substractions are wonky for the reasons i mentioned.

When looting, it seems that both buttons (loot item and loot stack) loot a single unit, but atleast the item is deleted properly on the loot sheet.

There is a small artifact that you probably already know about.
![image](https://user-images.githubusercontent.com/11763228/149147129-67785255-6009-45d5-be77-20800246c4d4.png)

And finally i get this error whenever i populate a sheet, it might aswell be an error with my own tables, but i tested with multiple.
![image](https://user-images.githubusercontent.com/11763228/149148672-3394e40d-7996-4c0e-91d8-c9ab541003c1.png)

**Comment by DanielBoettner** [comment]
@ABrandau Thanks for the feedback.

I push a new pre-release, like the one above, later today.

-----
* The artifact is a text shadow :D , it seems, thats needs a bit of refining.
* ✅ The error on line 105 is taken care of. Thanks for sharing.

I tested with another user. 
## Here are some "known issues".

* When using languages other than English, be sure that the rolltable you roll on references the items in the language that the compendium has the item names. Not yet sure if there will be a nice fix for that. 
* Make sure that users (and GM if GM wants to loot/buy) have a character assigned.
  * bottom left of foundry
  * configure user
  * click a character.
  * otherwise players wont show up in the sheet permissions field (GM always has permissions)
![image](https://user-images.githubusercontent.com/21986545/149152576-d1d70902-ca22-4036-b2c9-ca7777c7860b.png)
![image](https://user-images.githubusercontent.com/21986545/149152628-8a3d5e30-9ced-435c-a1c2-2c9e29c129aa.png)

* The styling (see GM section) seems to bug for some people. Did not yet manage to find out why. It just doesn't update the fields and give jquery warnings in the console.
* ✅when updating the sheet type via the actor, an error was triggered. This is locally fixed
* ✅Better rolltables was a dependency by accident (that was not intended to got public and is removed).

**Comment by DanielBoettner** [comment]
just zipped my latest dev build again. As always no guarantees :D
[lootsheetnpc5e-noErrorOnActorUpdate.zip](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/files/7855035/lootsheetnpc5e-noErrorOnActorUpdate.zip)

**Comment by ABrandau** [comment]
The error seems to be gone when i use the sheet, there are some warnings but it works.

On my end the artifact dissapears when you open the sheet for the first time after creating it, but then comes back next time you open the sheet.

The items are now substracted from the sheet as they should but the buy / loot stack and item buttons only substract a single unit from the sheet.

The option to add quantity might be broken, I am doing different tests, starting with a d20, then with 5, and I cant see a single item go beyond 2 units, in fact i had to change quantity manually to do the earlier test.

The sell option is a neat new feature, though I cannot find if there are any options to change the sell price of each item, as now they are sold at full price, and also I cannot change the currency of the merchant, i need to change to the default sheet to get my hands on it. (and yeah, there is an option to add currency to the sheet when populating the table), the windows might be a bit too small for that though.

![image](https://user-images.githubusercontent.com/11763228/149337186-ae482969-c522-4ef3-9fd0-962dac50a6af.png)

Finally i cannot recall if the sheet could populate scrolls from a spell compendium, i think it did but I might be wrong, in any case this does not work, but whenever I drag a spell into the sheet i get a spell scroll.

Sorry if I am covering too much ground but its these modules like yours what make foundry great, you are doing a great job.

**Comment by DanielBoettner** [comment]
If you find the time please test https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.5.5

It's honestly still a bit weird when changing settings(flags) in a sheet. But I think thats a broader issue to look into.
This should bring back functionality to the core functions, fix currencies, add styling (custom backgrounds, css tinting, darkmode), add actions, trading (well we could switch that off for now as it still lacks tooltips and other things, or we just say use it if you like).

Hit me if you have questions.

Their likely are still some bugs hidden. As I don't have multiple environments to test it in, certain things often just slip by.
So please feel encouraged to test it out.

Currently I prefer getting the bug reports via Discord. So as long as I still have the time to put that much time into this. I'd like to try to fix these things right away. :D

**Comment by RavenknightDM** [comment]
![Test](https://user-images.githubusercontent.com/53635985/150402055-b560e711-df32-41c7-988e-28802735287a.png)

This doesn't look right at the moment. But I'm glad that the sheet is still in development.
