### ISSUE TITLE
Loot sheets were not working at all, but I have included a fix in the description

### ISSUE THREAD

**Issue by gcolgate** [jopeek/fvtt-loot-sheet-npc-5e#249]
**Describe the bug**
In 9.242, somehow (maybe because  other modules) no loot sheets worked. I managed to fix them by sanitizing inputs.

My loot actors had incorrect currency. They were old actor first created in 8. something, but new ones did not work either. You could not click on the actor  or the token to bring up the loot sheet, it would spew an error.

Here is the fix, I added an IF statement inside convertCurrencyFromObject to fix it.
Perhaps there is another better fix.

Line 45 of LootHseetNPC5eHelper.js
```js
/**
     * Handles Currency from currency.TYPE.value to currency.TYPE for backwords support
     * @param {string} folderPath - The directory to loop through
     */
    static convertCurrencyFromObject(currency) {
        // fix for broken case
        Object.entries(currency).map(([key, value]) => {
            if (value) {
                currency[key] = value.value ?? value;
            } else { currency[key] = 0; }
        });
        return currency;
    } 
```

**Comment by DAMO238** [comment]
I can confirm that this is both an issue in the latest stable branch, and that this fix does solve the issue.

**Comment by DanielBoettner** [comment]
@jopeek @Varriount @Padhiver
If you find the time please test https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.5.5

It's honestly still a bit weird when changing settings(flags) in a sheet. But I think thats a broader issue to look into.
This should bring back functionality to the core functions, fix currencies, add styling (custom backgrounds, css tinting, darkmode), add actions, trading (well we could switch that off for now as it still lacks tooltips and other things, or we just say use it if you like).

Hit me if you have questions.

**Comment by DanielBoettner** [comment]
@DAMO238 @gcolgate

**Comment by gcolgate** [comment]
That fixed the problem I was having, there were some rendering glitches
looking at the sheet in the actor list, but double clicking on an icon made
it look more correct.

**Comment by gcolgate** [comment]
I will keep this prerelease version for my next full game to see if there
are any issues with it

**Comment by robnmeyer** [comment]
Daniel - would it be worth making a minor tweak to the existing Lootsheet as described gcolgate in order to quickly get lootsheet compatible with v9 and then work on this large enhancement as a separate parallel effort?  I played around with what you posted above; it's ambitious and will take some time to smooth out the edges.
