### ISSUE TITLE
[Feature Request] Party / Guild Treasury with Check-in / Check-out

### ISSUE THREAD

**Issue by AustinTiger** [jopeek/fvtt-loot-sheet-npc-5e#253]
**Is your feature request related to a problem? Please describe.**
No problem.  New usage model.

**Describe the solution you'd like**
Would like to expand the loot concept to a treasury or shared repository for a party, guild, etc.  New members could check out lower level gear that the OGs had deposited/donated as they have out-leveled the items.  

Loot sheet with per item option to either:
- Select/mark if the item is checked-in or checked out
- Specify name of PC (Actor) that has checked out the item.  Blank if available for check,

**Describe alternatives you've considered**
Manual solution since we are a small group where will ask eachother who has what.  Had spreadsheet but transitioned to loot sheet.

**Additional context**
No additional context, but a thank you for a module that has provided a lot of value and fun for our D&D group.  We've used it to create a Loot Goblin ala Diablo and have added a Treasury page and treasure chest (loot sheet) to our landing page.  Thanks again!

**Comment by DanielBoettner** [comment]
I get the basic idea.
But would honestly say this is a nice to have. Which I ,at least not personally, would not put much work in in the near future.

Don't get me wrong, I like the idea and even think this a "trivial" thing to implement.
However, there are a lot of things I'd like to see before doing this.

* I'd like to bring in another sheet type first. To better distinguish between a loot sheet being a slaughtered body or simply being a chest or other storage. 
* I'd like to have rolltables in the compendium) for each creature type to make the new automatic population feature more useful out of the box
* I'd maybe like to have an actor compendium with some ready to use merchants, thugs, and so on. Also ready to use, and it could showcase the use of sheet styling to even give GM's inspiration. And this would be a nice way to get in some easter eggs to pay tribute to other devs in the Community. 

I still very much appreciate that you (it seems) created a new account to share your idea (/make a feature request)

I really love the possibilities this module can bring for more immersive interaction with whatever the sheet represents.
And your idea would also fit in with an idea to optionally enhance each item obtained via a sheet to have info on where it was bought or from whom it was looted.

I hope I can give you 
Well as you hopefully see there is some stuff, and still bugs, to be taken care of first.
If you can code, you are more then welcome to help implement this.

**Comment by AustinTiger** [comment]
Thanks for the detailed response.  I know how to code but in early stages of the languages used by Foundry.  I've looked at this module's code some.  I'll see if I can hack something up and share.

Your ideas for the future sound great.  I look forward to them!
