### ISSUE TITLE
null property on currencies for old actors

### ISSUE THREAD

**Issue by Majea** [jopeek/fvtt-loot-sheet-npc-5e#254]
Depending on the version that was used to create an Actor, we may end up with currencies initialized in two different ways: 

```
"currency": {
			"pp": {
				"value": null
			},
			"gp": {
				"value": null
			},
			"ep": {
				"value": null
			},
			"sp": {
				"value": null
			},
			"cp": {
				"value": null
			}
		}
```

or 

```
		"currency": {
			"pp": null,
			"gp": null,
			"ep": null,
			"sp": null,
			"cp": null
		}
```
However, the current plugin code can only handle one of the two formats correctly. In the other case, we get a TypeError:

```
foundry.js:316 TypeError: Cannot read properties of null (reading 'value')
[Detected 1 package: lootsheetnpc5e]
    at LootSheetNPC5eHelper.js:51:35
    at Array.map (<anonymous>)
    at Function.convertCurrencyFromObject (LootSheetNPC5eHelper.js:50:34)
    at LootSheetNPC5e._prepareGMSettings (LootsheetNPC5e.js:789:60)
    at LootSheetNPC5e.getData (LootsheetNPC5e.js:68:14)
    at async LootSheetNPC5e._render (foundry.js:3059:18)
    at async LootSheetNPC5e._render (foundry.js:3761:5)
```
This prevents opening the Actor after the Loot sheet is used as character sheet.

Thank you all for your work!

**Comment by DanielBoettner** [comment]
Thanks for pointing that out. Could you share a json of an old actor that would trigger this error?
I would try to integrate some kind of migration for these old actors.

**Comment by Majea** [comment]
Of course. 
Here is a file that contains examples of both:
[actors.zip](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/files/7921341/actors.zip)

You can search for the id `5vccfdDOfnPzH7fh` for one with direct null values. The one with the id `Ccvdhh1gjD77wLnG` is one with the "value" property, but null as well.

**Comment by DanielBoettner** [comment]
https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.5.8
