### ISSUE TITLE
Merchant Purchased Item Not Transferred

### ISSUE THREAD

**Issue by EclypticWraith** [jopeek/fvtt-loot-sheet-npc-5e#261]
**Describe the bug**
When a player attempts to purchase any item from a Merchant, the correct currency amount is subtracted but the item is not added to their inventory, and is also not subtracted from Merchant's inventory. 

**To Reproduce**
1. DM creates a Merchant with some items given some currency value
2. Player is given "Observer" access to merchant and successfully accesses token
3. Player attempts to buy an item using either Buy Item or Buy Stack
4. Correct currency is subtracted from the player's inventory, but item is not added to player's inventory or subtracted from Merchant's inventory

**Expected behavior**
Currency is subtracted from player's inventory, item(s) are subtracted from Merchant sheet, and item(s) are added to player's inventory

**Screenshots**
<img width="733" alt="Player_Before" src="https://user-images.githubusercontent.com/99097672/152658628-4450b01b-bb23-4e4a-9981-2c24361f3157.png">
<img width="597" alt="Merchant_Before" src="https://user-images.githubusercontent.com/99097672/152658632-1f887fb7-fc3e-4fe7-b2cc-0a8b3c9c6285.png">
<img width="736" alt="Player_After" src="https://user-images.githubusercontent.com/99097672/152658634-07a82446-a1be-433e-8d84-0988e4a72566.png">
<img width="597" alt="Merchant_After" src="https://user-images.githubusercontent.com/99097672/152658636-9e80a2cc-91a7-4cc0-b91b-3378ac5f4311.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur (DM/Player), Windows 10 (Player)
 - Browser: Chrome
 - Foundry Version/Build: 9.249
 - System: DnD5e 1.5.6
 - Module Version: 3.4.1

**Additional context**
Does not seem to matter what type of item is purchased, whether item is custom or default, or whether the player sheet is locked or unlocked. Does still successfully give an error if not enough funds are present.

**Comment by Nedrapter** [comment]
I'm experiencing the same problem. My differences are:
Windows 10 both GM and players.
Opera, Chrome, Firefox browsers
It's been happening for the last 3 Foundry released versions (all 9.x)
