### ISSUE TITLE
Selected character is not recognized thus making it impossible to loot items from a loot-sheet

### ISSUE THREAD

**Issue by PragmaticBeaver** [jopeek/fvtt-loot-sheet-npc-5e#262]
**Describe the bug**
It is not possible to loot items from a loot-sheet, even if a character has been assigned to a player. The result will always be "No active Character for user.".

**To Reproduce**
1. Create new loot-sheet
2. Add Coins and Items to loot-sheet (doesn't matter which)
3. Set the loot-sheet permission using "Permission Configuration" (right click inside Actors Directory) to "Observer" for all players
3. Create new player character and assign it to your player
4. As the player, try to loot the loot-sheet using "Loot all items"
5. Error "No active Character for user" will be shown

**Expected behavior**
It should be possible to loot items as a player using an active character.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)

**Additional context**
***Possible Reason for the bug***
The active character is not recognized because the property "game.user.character._id" seems to be renamed into "game.user.character.id". This will result in a faulty check for an active character.
I was able to deduce this behavior from the following code inside the "LootSheetNPC5eHelper.js" row 141 - 144 (packaged version of the addon which was installed using FoundryVTT);
```
if ((!game.user.isGM && !game.user.actorId) || !game.user.character._id) {
    console.log("Loot Sheet | No active character for user");
    return ui.notifications.error(`No active character for user.`);
}
```

**Comment by PragmaticBeaver** [comment]
Edit:

FoundryVTT Version: 9 build 249

**Comment by DanielBoettner** [comment]
@PragmaticBeaver I currently only ever encountered this when people did not actually have a character assigned (left hand side).
Sometimes people also mistake the owner permissions on an actor for being the "assigning".

Please let me know if https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.6.5 solves the issue for you.
I think it should.

**Comment by PragmaticBeaver** [comment]
Yes, the nightly v.3.4.6.5 does fix the problem.
