### ISSUE TITLE
Invalid module.json prevents module update

### ISSUE THREAD

**Issue by Majea** [jopeek/fvtt-loot-sheet-npc-5e#272]
**Describe the bug**
The Loot Sheet NPC 5e can no longer be updated. 

**To Reproduce**
1. Start and log in to Foundry VTT (V9.249)
2. go to the Modules tab
3. update all the modules
4. A dialog opens saying the Loot Sheet NPC 5e cannot be updated because "The request to http://.../module.json did not provide a valid manifest file.

**Expected behavior**
The module updates correctly

**Screenshots**

![loot_sheet_npc_failed_update](https://user-images.githubusercontent.com/3779503/153637681-21c466dd-5583-4a8a-a668-4eb610b64669.png)

**Comment by timartiny** [comment]
Same happened to me

**Comment by DanielBoettner** [comment]
If this issue is still relevant.
Try to uninstall the module and use the module.json at the end of the readme.
But I tested that the modul can be installed that way.

Could be that we have to change the url in the foundry admin @jopeek ?

**Comment by timartiny** [comment]
Seems like it needs to be changed in Foundry: uninstall and reinstall through foundry fails also, giving "The request did not provide a valid manifest file"

But installing with manually putting in the manifest in the README worked.

**Comment by blightbow** [comment]
> Seems like it needs to be changed in Foundry: uninstall and reinstall through foundry fails also, giving "The request did not provide a valid manifest file"
> 
> But installing with manually putting in the manifest in the README worked.

This worked for me as well. The URL in the README points at master/src/module.json, but the Foundry installer is looking for it at master/module.json. Uninstalling the module and reinstalling it does not address this.

**Comment by jopeek** [comment]
This should be resolved now. Latest version is 3.5.2.
