### ISSUE TITLE
BUG: Adding coins doesn't work, symbols missing and sheet cut off.

### ISSUE THREAD

**Issue by GabrielOsvair** [jopeek/fvtt-loot-sheet-npc-5e#274]
(Google Translator) Hello! I was waiting for the update and I loved the changes. I noticed that generating coins in sheets is not working! Either by adding it through the form itself or configuring it to be added automatically.

Another issue is that I don't know if it's intentional, but there are two symbols that appear as "squares", but I imagine it must be another one.
*Here on the button to pick up a unique item:
![image](https://user-images.githubusercontent.com/67530921/153688104-6b42d7b8-0153-4449-8263-788f3c635231.png)

*Here in two places in the permissions section and in the dark theme:
![image](https://user-images.githubusercontent.com/67530921/153688189-59f2598d-06c7-43f4-8a60-23d3e66b03a6.png)

Finally, when the sheet is opened, its automatic size cuts part of the coins at the bottom of it.
![image](https://user-images.githubusercontent.com/67530921/153688301-22ca4bdd-de38-4bd4-b387-5f9e4640d285.png)

```
Foundry Virtual Tabletop: Version 9, 9.249
Game System: dnd5e, 1.5.7
Active Modules: 4
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1165)
Max Texture Size: 16384

Scene: 3000 x 3000 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2

Actors: 89 | Items: 32 | Journal: 0 | Rollable Tables: 3 |
Playlists: 0 | Compendium Packs: 19 | Chat Messages: 2
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: last

**Comment by GabrielOsvair** [comment]
I think I must be doing something wrong, but I just can't generate coins in the sheet! I tested several configurations.

**Comment by DanielBoettner** [comment]
Here is what I have

![image](https://user-images.githubusercontent.com/21986545/154101149-dbb8c78d-0fe6-4b5e-b2ce-0a79afa3dd7e.png)

Please make sure your on version 3.5.7
