### ISSUE TITLE
Can't create new merchant

### ISSUE THREAD

**Issue by hframos4** [jopeek/fvtt-loot-sheet-npc-5e#276]
I just made this doc to report this problem I'm having to create a new merchant
[Bug Report](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/files/8052526/Bug.Report.docx)
Don't know if all informations are here, but you contact me if need more

**Comment by zdaar** [comment]
I have the same issue on the same build

**Comment by DanielBoettner** [comment]
Please copy the content of your bug report to this issue.

**Comment by DanielBoettner** [comment]
you can test if your problem persists  with the latest release https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/v3.5.8

**Comment by hframos4** [comment]
> Please copy the content of your bug report to this issue.

I would like to report some bugs, don’t know if it’s Only happening with me but, since last update (witch changed the url) I’m unable to create new merchant, and everything turned to lootsheet, and even though I’m unable to loot the NPC

The first error already appears after I load my world
![Imagem1](https://user-images.githubusercontent.com/88849691/154775194-90f17d65-0e8a-4e58-a9b6-d09be8c803e7.png)
And with my NPC that supposed to be a merchant
![Imagem2](https://user-images.githubusercontent.com/88849691/154775215-e6e1b55e-7ea1-402c-b1d0-dc5113338b22.png)

First I changed the sheet type to lootsheetNPC5e
![Imagem3](https://user-images.githubusercontent.com/88849691/154775249-fe3c448d-b548-4c53-9fb8-db035de09707.png)
eetNPC5e
When I click here to change to merchant, the following happen
1 before I click, everything is normal
![Imagem4](https://user-images.githubusercontent.com/88849691/154775290-1fb0c55a-1fc6-4a36-8ed7-4ddf3cadd6bc.png)

2 after I click, the middle tap change to trade, but the “sheet type” flashes in merchant than turn back to loot
Even if I change the sheet back to merchant, it doesn’t save the configuration, if I close and reopen, it came as loot sheet
That’s the first issue
The second is that the real lootsheet, I can’t loot from this same NPC that suppose to be a merchant 
When I click on any button to loot with my PC, this error shows up when clicking to loot on item
![Imagem5](https://user-images.githubusercontent.com/88849691/154775328-bdba39d9-dc73-4f27-a572-7e319b328d67.png)
And this error shows up when clicking to take all
![Imagem6](https://user-images.githubusercontent.com/88849691/154775366-89345134-3fa8-4404-8285-a1625741e720.png)

I don’t know any more information to tell, fell free to DM if you need more
I’m using the latest version of foundry (9.249) and module (3.5.2)


Sorry for the late response

**Comment by hframos4** [comment]
@DanielBoettner now when I click here
![Imagem1](https://user-images.githubusercontent.com/88849691/154775670-a9ccfafb-9842-4e23-a72b-9085b71cf604.png)

the sheet closes and do not open again
and on the console, show this
![Imagem2](https://user-images.githubusercontent.com/88849691/154775742-f15ca8fc-3a1b-46a2-ae63-c4d4ef698262.png)

and when click on the actor, it do not show me the sheet

**Comment by hframos4** [comment]
it's not saving when changed to merchant, if I click then close, when opened again it became a loot sheet again
![image](https://user-images.githubusercontent.com/88849691/154777289-4f05a89c-9ebc-49a6-a2e6-a2fd2c1af55c.png)
but do show any error

**Comment by hframos4** [comment]
if I change the sheet type to merchant and leave it open, when a player interacts with it, it look like a merchant, if i close, it turn back to loot sheet

another thing i discoverd when doing this test, the first time the player buy someting on the merchant it charges the double amount of GP (for exemple) and do not show on the chat log, the second time charges normal and shows on chat log,

but when looking the player inventory, there was the 2 itens bought

**Comment by DanielBoettner** [comment]
> if I change the sheet type to merchant and leave it open, when a player interacts with it, it look like a merchant, if i close, it turn back to loot sheet

I was not able yet to find out why this happens.
I got this issue sometimes. sometime not at all.

Closing the sheet after a change in the GM settings could help.

**Comment by hframos4** [comment]
Ok, here's the deal, the thing with the sheet not being able to save whatever it was a merchant or loot, solved 

but now there this error whan a PC tries to buy someting
![image](https://user-images.githubusercontent.com/88849691/155051534-f45f462e-acad-492b-9983-8abdfcfc4fbf.png)

and this, potencial same error, when tries to buy a stack of itens
![image](https://user-images.githubusercontent.com/88849691/155051714-f4b9f1b6-ce7e-4dd5-92f9-7c41210f6cd3.png)

**Comment by hankland39** [comment]
I'm also having the same problem. Only way to get a merchant sheet to even display for players is to manually change the sheet to merchant and keep the sheet open as the GM. If you close the sheet in any way it reverts it back to a loot sheet.

**Comment by DanielBoettner** [comment]
This should hopefully be fixed in the latest release.
Please create a new issue if the problem persists.
