### ISSUE TITLE
Disabling option for Create Loot buttons doesn't disable toolbox button, for GM or players

### ISSUE THREAD

**Issue by ianm32** [jopeek/fvtt-loot-sheet-npc-5e#278]
With the option "Add interface buttons" unchecked, the button in the Foundry toolbox is still visible.

![bug](https://user-images.githubusercontent.com/27756065/153736539-0ce3a02b-9c86-4b6a-86d9-675b018f920d.jpg)

On the same topic a [FEATURE REQUEST] - Have the option for this button's visibility to be separate for GM and players.  I can't think of a reason in my game that players would need to generate loot for an NPC.

Thanks!

**Comment by DanielBoettner** [comment]
I tried to patch that, for now can't do it.
As the hook is to early. But will keep that in mind and change the description accordingly
