### ISSUE TITLE
values below 1 gp are sold free of charge

### ISSUE THREAD

**Issue by rinnocenti** [jopeek/fvtt-loot-sheet-npc-5e#280]
**Describe the bug**
buy from a merchant fractional amounts are ignored, but the purchase is made

**To Reproduce**
create an item with fractional values
put it on the merchant token
buy using a character sheet

**Comment by DanielBoettner** [comment]
This likely is a rounding issue.

The relevant code is likely 
 https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/21fcc79be528820bec3e585fee1b18d057d42a5d/src/modules/helper/TradeHelper.js#L315

```js
 // Add item price to the total sum of the trade
            tradeSum += Math.round(((item.data.data.price * priceModifier * 100) / 100) * item.data.data.quantity);
```

At least thats what is used in the method updating the funds.

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/21fcc79be528820bec3e585fee1b18d057d42a5d/src/modules/helper/TradeHelper.js#L406

And I suspect that the item price is deducted from the funds.

But later on in the handling of the funds these kind of minimal changes are cut of during rounding when smoothening the funds.

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/21fcc79be528820bec3e585fee1b18d057d42a5d/src/modules/helper/TradeHelper.js#L473

This is where the module tries to get the parts of higher currency and converts them to parts of lower currency.

```js
 for (let currency in funds) {
            let current = funds[currency].toFixed(5),
                currentPart = (current % 1).toFixed(5),
                currentInt = Math.round(current - currentPart),
                compCurrency = compensation[currency];

            funds[currency] = (currentInt > 0) ? currentInt : 0;

            if (currency != "cp") {
                // We calculate the amount of lower currency we get for the fraction of higher currency we have
                let change = currentPart * rates[compCurrency];
                funds[compCurrency] += change;
                console.log(`${MODULE.ns} | TradeHelper | updateFunds | Updated ${compCurrency} by ${change} it is now ${funds[compCurrency]}`);
            }
        }

        return funds;
```

So I suspect that on either parts (or both) the rounding should be looked at again.
And that during smoothing (so converting) of the funds these small changes just do not trigger the funds to round down.

**Comment by DanielBoettner** [comment]
This should be fixed in https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/v3.5.8
