### ISSUE TITLE
User lacks permission to update Token in parent Scene

### ISSUE THREAD

**Issue by AutomatonTec** [jopeek/fvtt-loot-sheet-npc-5e#284]
**Describe the bug**
Player gets an error notification when I drop tokens into the scene

**To Reproduce**
- drop a new Actor into the scene
- Players get an error notification

**Expected behavior**
No error notifications

**Screenshots**
![Screen Shot 2022-02-14 at 18 39 33](https://user-images.githubusercontent.com/1485158/153982513-5e0a3c23-3556-466d-b7d6-a3a27e6dc1fc.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.3
 - Browser Safari

**Comment by DanielBoettner** [comment]
* Any more information in the console (F12)?
* Can you test if the error also occurs on other browsers?

**Comment by AutomatonTec** [comment]
Fixed with the update :) 

Thanks
