### ISSUE TITLE
Cannot open or generate any loot

### ISSUE THREAD

**Issue by EmkooVision** [jopeek/fvtt-loot-sheet-npc-5e#292]
Clicking the button "Generate Loot for selected Token" does nothing. No Menu, no window, no table...

Error message in all Browsers (Chrome, Firefox, Edge):

foundry.js:2534 Uncaught (in promise) TypeError: uuid.split is not a function
[Detected 1 package: lootsheetnpc5e]
    at fromUuid (foundry.js:2534:20)
    at Function.seedItemsToActors (modules/lootsheetnpc5e/lootsheetnpc5e.js:11:69285)
    at Object.onClick (modules/lootsheetnpc5e/lootsheetnpc5e.js:11:111096)
    at SceneControls._onClickTool (foundry.js:51610:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at HTMLLIElement.v.handle (jquery.min.js:2:41048)

Right click on Token and on the "eye" also does nothing, and no error message.

Versions:

Foundry Version 9 - Build 249
Dnd5e 9.249
Foundry is running on a raspberry pi, same error on desktop version
Windows 11

Are there any requirements in the form of other modules?

**Comment by DanielBoettner** [comment]
Please check if the error persists with the latest version.
https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/v3.5.8

If so, please check the settings for the lootsheet.
The seeder should have some table assigned somewhere. 
Or you assign a rolltable directly to the actor.

The only hard requirement currently is dnd5e.
A soft requirement is mentioned in the welcome screen.
