### ISSUE TITLE
v0.6.0 compatibility issue

### ISSUE THREAD

**Issue by toadicusrex** [jopeek/fvtt-loot-sheet-npc-5e#30]
Just upgraded to v0.6.0 of Foundry, found an error that only happens when loading the loot sheet.  I'm going to try to dig in a little, but I need to get my game running for Thursday night first. :)

Uncaught SyntaxError: The requested module '../../systems/dnd5e/module/actor/sheets/npc.js' does not provide an export named 'default'

If I disable this module, no error.

**Comment by jopeek** [comment]
Your dnd5e is likely out of date. It has to be 0.9+

**Comment by toadicusrex** [comment]
Indeed - you were correct!   Thank you!  I appreciate it!
