### ISSUE TITLE
Question: Why am I getting the message "you need to assign an actor to your user before you can do this", when trying to loot a monster?

### ISSUE THREAD

**Issue by wgrasham** [jopeek/fvtt-loot-sheet-npc-5e#303]
Question: Why am I getting the message "you need to assign an actor to your user before you can do this", when trying to loot a monster?
When I select a monster to loot (which has already been converted to lootable) I can see the items to be looted (see attached image), but I can not loot them because no character (actor) appears in the view to the right, to which the loot can be assigned. 
I am confused why my character does not appear in the window and how to fix this.
![error message](https://user-images.githubusercontent.com/100097973/154869461-9e05527b-394b-4630-8183-d80eaaf5c241.jpg)

**To Reproduce**
1. Convert a dead monster to lootable
2. Click on the monster
3. Go to the tab for “Loot”
3. Notice that no character shows up in the window under “biography”, where the character is to be selected, who would receive the loot.
4. Notice the error message, “you need to assign an actor to your user before you can do this",

**Expected behavior**
I would expect to see a character appear, because I created the actor that I am using to loot.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - Browser Firefox
 - Version: 97.0 (64 bit)

**Additional context**
none

**Comment by wgrasham** [comment]
My User ID has the permission of "owner" to the actor called "Test PC" and the token has data linked to the actor. So I am not sure what I have to do to assign an actor to my User-ID other than what I have already done

**Comment by wgrasham** [comment]
I cannot get the LootSheet to recognize actors on the active map.
As you can see in the screen shot, only two actors are being recognized. It is the same issue regardless of whether I am dealing with a monster that is being looted or a merchant.
Is anyone else having the same issue?
It appears to be a bug.
![actor issue](https://user-images.githubusercontent.com/100097973/154962408-91689c0b-b212-45ab-856e-c1695ae62f49.png)

**Comment by DanielBoettner** [comment]
In discord you mentioned there should 5 actors you expect to see.

Do all 5 actors have this user<--> actor assignment?
In other words, are there 5 users (players and GM) that have picked an actor they have owner permissions on
in the left bottom user configuration?

**Comment by wgrasham** [comment]
There are three players (users).  

  

However, one of those three users is a user-ID created by me (the DM) for
testing purposes. (The token that I used for testing is called "Test PC",
which has no token image.)  

  

In the Loot sheet screen shot there are only 2 actors showing as having access
to either loot or to trade with the merchant.  

  

There should be 3 actors showing up. One test actor for the DM and one actor
for each of the two other users.  

  

One user is missing entirely. Neither of his two actors show up in the screen
shot as having any access and in game testing has demonstrated that he does
not have any access.  

  

The user that shows up in the screen shot does have access. (One of his two
actors shows up in the loot sheet screen shot.)

  

Bill Grasham

**Comment by wgrasham** [comment]
So I was able to test out the changes that you recommended below and it
worked.  

  

Now one of the two actors belonging to each user-id is able to loot a dead NPC
and is able to buy and sell with the merchant.  

  

Thank you very much for your help with this issue.  

  

Bill Grasham  

  

  

On Wednesday, February 23, 2022 6:50 AM, "Daniel Böttner"
***@***.***> wrote:  

>  
>
>
> Did you and/or your players check if you did what is described  
>
>
> in these links ?  
>
>
>   * <https://foundryvtt.com/article/player-orientation>  
>
>   *
> [https://foundryvtt.com/article/users](https://foundryvtt.com/article/users/#create)  
>
>

>
> Your last answer came via mail, so maybe these weren't really visible.  
>
>

>> In the Loot sheet screen shot there are only 2 actors showing as having
access  
>
>>

>> to either loot or to trade with the merchant.  
>
>
> Likely one player and your GM character. If you hover the mouse over the
> visible players you should see which actor controlled by which player.  
>
>

>> There should be 3 actors showing up. One test actor for the DM and one
actor  
>
>>

>> for each of the two other users.  
>
>
> So only one is missing? Likely the missing player has not assigned a
> character.  
>
>

>> One user is missing entirely. Neither of his two actors show up in the
screen

**Comment by DanielBoettner** [comment]
>  I think it might be because the players did not have permission to change settings...
if you ever come to test that theory, feel free to let me know.
