### ISSUE TITLE
Settings updating is glitchy

### ISSUE THREAD

**Issue by Nedrapter** [jopeek/fvtt-loot-sheet-npc-5e#304]
**Describe the bug**
I'm setting up some new npc sheets with this module and changing any setting in the 1st tab ignores my choice the first time. For example I change the sheet from Loot to Merchant, it shows Merchant for a split second the reverts back to Loot. Doing a 2nd time works normally. Every setting requires to change it twice to work.
Furthermore some settings revert back to the default at seemingly random points. After chaning Loot to Merchant and fiddling with some other settings or closing and re-opening the actor sheet, the Merchant reverted back to Loot.

**To Reproduce**
Change a setting

**Expected behavior**
To apply changes the first time and remember the setting.

**Desktop (please complete the following information):**
 win 10
 Opera, Firefox, Chrome

There's no error on the console while this is happening. I deactivates all other modules and the issue still continued.

**Comment by aruguy** [comment]
I'm having the same issue, on win10/Firefox.  Nearly all setting fields require multiple change attempts before the desired setting "sticks".

**Comment by DanielBoettner** [comment]
This should be fixed with 3.5.14.

Feel free to create a new issue if you still encounter this problem.
