### ISSUE TITLE
Error when generating from loot table that results in text.

### ISSUE THREAD

**Issue by weihanderz** [jopeek/fvtt-loot-sheet-npc-5e#306]
**Describe the bug**
In cog wheel tab, generate loot on a loot table which has text as one of the results (Such as a trinket table or the canned item table on the loot table). If the generated loot is a text result, this error will occur:

`Uncaught (in promise) TypeError: this._parseTextResult is not a function
[Detected 1 package: lootsheetnpc5e]
    at LootProcessor._parseResult (LootProcessor.js:156)
    at LootProcessor.buildResults (LootProcessor.js:44)
    at async Function.addLootToTarget (ActorHelper.js:171)
    at async Function.seedItemsToActors (LootSeeder.js:35)
    at async SheetListener.inventoryUpdateListener (SheetListener.js:164)
_parseResult @ LootProcessor.js:156
buildResults @ LootProcessor.js:44
async function (async)
inventoryUpdateListener @ SheetListener.js:167
(anonymous) @ SheetListener.js:90`

**To Reproduce**
1. Go to a character sheet using the loot sheet npc 5e
2. Use a table which has a text result
3. Click update

**Expected behavior**
Expected result should generate an item that has a name/description of the text

**Screenshots**
![image](https://user-images.githubusercontent.com/35861092/155204077-c5830870-16a0-4dc7-a3cf-eae59e45d8be.png)
![image](https://user-images.githubusercontent.com/35861092/155204107-53a41029-ce9a-4990-9288-6bfe1e37d95c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Foundry Electrum
 - Version Foundry v9 Build 249, Lootsheet NPC 5e v3.5.9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielBoettner** [comment]
Thanks, will fix this in the next release

**Comment by DanielBoettner** [comment]
Should be fixed in version 3.5.10, or a new error relating to parsing text results 🙈
