### ISSUE TITLE
Splitting currency erases possible remainder

### ISSUE THREAD

**Issue by Nivrelin** [jopeek/fvtt-loot-sheet-npc-5e#314]
**Describe the bug**
When the currency is split between the party what ever couldn't be split is just lost

**To Reproduce**
1. Split currency not cleanly divisible by number of players
2. see no money on npc anymore

**Expected behavior**
For example if I have 5 players and the lootsheet has 6cp, i expect 1cp to stay after the split.

**Comment by mrwalters1988** [comment]
I'm also having issues with this. What's worse is that higher denominations aren't converted either, they're just lost. 
E.g. I have 1 gold and 4 silver divided amongst 4 party members. Each party member receives 1 silver and the gold is discarded.
