### ISSUE TITLE
[Feature request] quick item quantity change

### ISSUE THREAD

**Issue by SLinxTheFox** [jopeek/fvtt-loot-sheet-npc-5e#316]
It'd be really useful if i could click on the quantity and type in a number to change it to that number. I think past versions might have done this before too

Basically i'd like it to go from this
![jb7LI7a](https://user-images.githubusercontent.com/44953602/156078818-bbc8b09e-d499-4831-adf7-1d093d48af7d.png)

to this
![gtZNCAy](https://user-images.githubusercontent.com/44953602/156078836-cea984cf-562d-45b7-b4c5-da57093baba4.png)

**Comment by DanielBoettner** [comment]
Agreed, already have this in mind.
Can't say yet how fast I will be able to get to it.
