### ISSUE TITLE
Player cant loot/buy a item

### ISSUE THREAD

**Issue by Gvicross** [jopeek/fvtt-loot-sheet-npc-5e#317]
Hello,

The module Its awesome, but actually its been frustrating. My players cant loot a item for the sheet. I've been trying with ALL modules inactives and still not working. Just work when me GM, set a char for me, so the module works normal, but to players... Not.

Ps. I suspect of one thing. My players haver mounts, Sheet of itens set for they like "Own/propertie", maybe the module dont reconigze for what those characters they to have transfer the item. 

Sorry for the english, im Brazilian Noob.

**Comment by HallweenKiller** [comment]
The same thing is happening to me, I used the find the culprit module and it deactivated all other modules and then came to the conclusion that it was a bug with LootSheetNPC itself.

**Comment by rafaeladson** [comment]
I am also having a problem.

When I see the permissions page I see my players have there and have permissions, but when I see the loot sheet it says "split currency among 0 party members".

Not sure what I am doing wrong.

**Comment by DanielBoettner** [comment]
Please check the things mentioned in the linked comment (an following):

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/303#issuecomment-1047525243
