### ISSUE TITLE
Feature Request: Allow GM to remove "Generate Loot Button" from player settings 

### ISSUE THREAD

**Issue by davidhawbecker** [jopeek/fvtt-loot-sheet-npc-5e#320]
Man, this is a popular module. I don't envy how busy you are with this and I sincerely appreciate your time and effort. This is definitely one of the game change modules for foundry.  So far I love everything you're doing, I just have one small request if it's at all feasible. I'm not sure why the players would need a button for "Generate loot for the selected token" and I know once I enable this, they will find it and they will ask about it and of course, try to use it, which I know they cant with their permissions, but that why I'm not sure they have access to it in the first place. Again, not a big deal, but I figure it couldn't hurt to ask. I really love your stuff man. Keep it up.

**Comment by Gvicross** [comment]
Has the module worked for you? My players haven't been able to buy or loot anything.

**Comment by davidhawbecker** [comment]
Honestly I only really use lootsheet for the loot generator/seeder function
and then I use Item Piles for the players to loot bodies and containers.
For shops I use either Merchant Sheet or Monks Enhanced Journal.

**Comment by DanielBoettner** [comment]
> Has the module worked for you? My players haven't been able to buy or loot anything.

Please check the things mentioned in the linked comment (an following):

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/303#issuecomment-1047525243

**Comment by DanielBoettner** [comment]
> Man, this is a popular module. I don't envy how busy you are with this and I sincerely appreciate your time and effort. This is definitely one of the game change modules for foundry. So far I love everything you're doing, I just have one small request if it's at all feasible. I'm not sure why the players would need a button for "Generate loot for the selected token" and I know once I enable this, they will find it and they will ask about it and of course, try to use it, which I know they cant with their permissions, but that why I'm not sure they have access to it in the first place. Again, not a big deal, but I figure it couldn't hurt to ask. I really love your stuff man. Keep it up.

In short, I will look into it.
The buttons should not be visible to players. Will check why they see it.
Don't know how fast I get to it.

**Comment by TRawss** [comment]
I can't get the "generate loot" button removed from my player's view either.
