### ISSUE TITLE
You need to assign an actor to your user before you can do this

### ISSUE THREAD

**Issue by arcanjl** [jopeek/fvtt-loot-sheet-npc-5e#321]
![image](https://user-images.githubusercontent.com/29612539/156907773-c5ef2469-b415-43a0-b1cd-63dde9b37a70.png)

This is happening when any of my players try to take an item - what am I doing wrong?

**Comment by DanielBoettner** [comment]
Please check the things mentioned here:

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/303#issuecomment-1047525243
