### ISSUE TITLE
Players cannot loot or trade from an actor or linked token

### ISSUE THREAD

**Issue by matt-saunders1996** [jopeek/fvtt-loot-sheet-npc-5e#324]
**Describe the bug**
Players cannot loot or trade from an actor or linked token: but can from an unlinked token. I haven't been able to find anywhere if this is by design or not, so apologies if it is. All my players have their characters configured properly. FWIW I am trying to do this so each player can have their own backpack to store things in and drop in combat as they please.

**To Reproduce**
1. I log in as a player, and having seen that the Backpack actor is visible to me, open its sheet,;
2. Items in the loot screen, when clicked, DO transfer to the middle, but clicking confirm has no effect. 
3. I do not get any console errors when clicking confirm
4. I do however, get yellow some console messages when opening the sheet:

```
OTS parsing error: cmap: Failed to parse table
foundry.js:3053 Foundry VTT | Rendering LootSheetNPC5e
PermissionHelper.js:157 lootsheetnpc5e | PermissionsHelper | getEligablePlayerActors | 5 players with eligable characters found.
game:1 Failed to decode downloaded font: https://----------------[]removed by me]
game:1 OTS parsing error: cmap: Failed to parse table
```

**Expected behavior**
Lootable actor sheet

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Brave
 - Version: couldn't find easily, apologies

**Additional context**
- Setting players' permissioon to owner does not help, and in fact completely removes the ability to transfer items *to the middle8 on the loot screen.
- I suspect some other module is the cause, as I am running quite a few. Here is the list:
`Active Modules:
----------
About Time v;
Absolute Hotbar Keybindings v;
Actually Private Rolls v;
Advanced Macros v;
Advanced Spell Effects v;
Argon - Combat HUD v;
Autocomplete Inline Properties v;
Automated Animations v;
Auto-Rotate v;
Better Text Drawings v;
Combat Carousel v;
Combat Numbers v;
Combat Utility Belt v;
Custom Fonts v;
D&D 5th Edition PHB Journal Styling v;
DFreds Convenient Effects v;
DFreds Effects Panel v;
Dice Tray v;
Drag Upload (Get Over Here!) v;
Dramatic Rolls v;
Drop My Torch v;
Dynamic effects using Active Effects v;
Easy Target v;
Faster Audio Preload v;
Forien's Quest Log v;
Foundry Community Macros v;
FoundryVTT Mount Up! v;
FXMaster v;
GM Screen v;
Initiative Quick Change v;
Item Macro v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Less Fog v;
Let Me Roll That For You! v;
lib - Color Settings v;
libWrapper v0;
Lock View v;
LootsheetNPC5e v;
Midi QOL v;
Minimal UI v;
Monk's Enhanced Journal v;
Moulinette Core v;
Moulinette Sounds & SoundPad (module) v;
Patrol v;
Perfect Vision v;
Pings v;
Playlist Importer v;
Polyglot v;
PopOut! v;
Search Anywhere v;
Sequencer v;
Settings Extender v;
Shared Vision v;
Simple Calendar v;
Smart Doors v;
socketlib v;
SoundBoard by Blitz v;
SoundBoard Pack - Blitz Free Pack v;
SoundBoard Pack - Community v;
Splatter v;
Tabbed Chatlog v;
Tagger v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Token Attacher v;
Token Info Icons v;
Token Z v;
Trigger Happy v;
Warp Gate v;
Window Controls v;

Inactive Modules:
----------
Ammo Tracker v;
Better Roofs v;
Class Exposure v;
Class Leveling Editor v;
D&D Beyond Importer v;
DFreds Droppables v;
DnD5e Helpers v;
Dnd5e Helpers Cover Expansion v;
Ensemble - drag and drop your sound files v;
Foundry Community Tables v;
Hero Creation Tool for DnD5E v;
Hey, Wait! v;
Hidden Soundtracks v;
Hurry Up! Combat Timer v;
Inline Webviewer v;
Item Piles v;
Loot populater NPC | 5e v;
Maestro v;
Magic Items v;
Not Your Turn! v;
Playlist Drag and Drop v;
Roll Table from Sidebar and Journal v;
RPG Styled UI for Foundry VTT v;
SoundFx Library v;
SWADE ES, CA, GL, EU translation v;
Tablesmith like Tables v;
The Furnace v;
Times Up v;
Token Auras v;
Tokenizer v;
Turn Marker v;`

Thanks in advance

**Comment by DanielBoettner** [comment]
I will take a look at this. 
This is not by design. But could be a side effect of some precautions.
There is another issue open wich maybe related.

I have to test this a bit before I can say more. Please be patient. :)
