### ISSUE TITLE
Cant Open Merchant Npc Actors

### ISSUE THREAD

**Issue by CurzedPrizma** [jopeek/fvtt-loot-sheet-npc-5e#325]
**Describe the bug**
When trying to press the actor in the side menu, nothing happens, even as a GM you are locked out.

**To Reproduce**
1. Make a new npc
2. make the character sheet into the Loot sheet.
3. In the **filter options** choose the `-"- view the scene & have token active` option.
4. Now close the sheet again.

**Expected behavior**
The gm being able to open it

**Screenshots**
![2022-03-11 16_53_50-The Lost Island • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/101415914/157901906-2bf8ca1b-521c-48c6-958d-a9446f84e5f6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Program Version: 3.5.10

I don't know how the filter option is supposed to work. Thanks.

**Comment by TheGMOrsini** [comment]
I am having the same issue.

**Comment by HeartlessGamerX** [comment]
I am having this same issue.

**Comment by DanielBoettner** [comment]
I will test later if this issue still persists.
