### ISSUE TITLE
Players cannot loot / trade with any of LootSheet

### ISSUE THREAD

**Issue by Aymeeeric** [jopeek/fvtt-loot-sheet-npc-5e#326]
**Describe the bug**

Hi! A little (?) problem on my side. 
I think I have perfectly configured my loot sheets (nothing fancy here) and my players are well assigned to an actor (only one).
When a player tries to interact with a loot sheet, for which he is the owner and has all the rights, it opens but he cannot do anything with it.

In console, I have systematically this stack:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/15995376/158014263-d2493db4-cd3f-4856-900f-931f696cf4e0.png">

Thank you in advance, and don't hesitate to tell me if I can bring more relevant information!

**Comment by Aymeeeric** [comment]
After uninstalling and reinstalling the module, resetting all its settings and checking that each player has a dedicated token: always the same thing.

When a player opens the form of a loot actor, he gets the following error in the console:

![image](https://user-images.githubusercontent.com/15995376/159163218-6e9e6677-043f-4eb9-afbf-556a8b37e522.png)
![image](https://user-images.githubusercontent.com/15995376/159163221-270eadb2-394a-4414-b638-b61548642ec3.png)

**Comment by webmaster94** [comment]
Can confirm I am getting the same behavior. I see this was reported a month ago. I see that it hasn't been updated in two months either. I am not sure if the author is just taking a break or if they are no longer actively developing this module.

**Comment by Aymeeeric** [comment]
It seems that this module is no longer maintained...
While waiting for an update, I switched to [Monk's Enhanced Journal](https://github.com/ironmonk88/monks-enhanced-journal) which does the job very well!

**Comment by webmaster94** [comment]
That's what I am using now as well.

**Comment by DanielBoettner** [comment]
If you like, feel free to test the latest release.
I started a new job and hadn't had much time the last two months.

I fixed some other issues and did not encounter this issue myself.
If the error persists with the latest version I can take a look.

**Comment by DanielBoettner** [comment]
After reading you description again. I'm almost sure the issue will still be in the latest version.
Will have to take a look at it. But this can take some time.
Will have to figure out which parts are impacted.

Could you describe the "use case" in more detail?

**Comment by ironocy** [comment]
I'm getting a similar error when players try to buy something from the merchant sheet. It's a new problem that recently started happening. Either it doesn't let them buy anything or only buy one thing before it stops letting them buy anything. I've tried a linked and unlinked to actor merchant sheet. Happens with every merchant and PC.
![Merchant](https://user-images.githubusercontent.com/49377788/182024160-04ba25a5-2da3-42dd-a3b9-ea6749789191.png)

**Comment by IanYuy** [comment]
I haven't been able to have the players loot from a loot sheet for a long while, now. Both currency and item looting just nothing when clicked. Our use case is a loot sheet actor that we use as the party inventory, where we place all gained loot and then divvy amongst ourselves.

**Comment by DanielBoettner** [comment]
Very sorry for the delay.
Still working on converting the lootsheet to typescript for better code stability. 

As I only can spare a limited time, this takes a while.

However, bugs like these should be less likely in the future.
I can only ask for patience.

**Comment by Terrox** [comment]
I think this is how to reproduce the issue:
try trading as a player with Lootsheet "loot" token.
- Lootsheet does not trade with linked actor-token.
- Lootsheet does trade with unlinked token.

Therefore cannot use a Lootsheet as a player controlled Henchman or Tensers Disc to hold items between scenes. (no linked sheet).
