### ISSUE TITLE
Not possible to Install on 0.8.9

### ISSUE THREAD

**Issue by JuIez** [jopeek/fvtt-loot-sheet-npc-5e#327]
**Describe the bug**
I can't install the Module on Foundry-0.8.9, because of a not valid manifest file.

**To Reproduce**
1. Go to 'Add-on Modules'
2. Click on 'Install Module'
3. Search for 'loot sheet'
4. Press Install
5. See error

**Expected behavior**
Dunno, should Install

**Screenshots**
![image](https://user-images.githubusercontent.com/44580956/159130375-c123662f-555f-41e0-874e-0023bd59e26c.png)

**Server (please complete the following information):**
 - OS: Ubuntu
 - With Docker: felddy/foundryvtt:0.8.9]

**Comment by jopeek** [comment]
The latest version is not compatible with versions prior to 9. 

There is an older release in the releases page that still works with it. Alternatively, upgrade to 9.
