### ISSUE TITLE
Breakage when Roll Tables have individual currency items

### ISSUE THREAD

**Issue by gaschw3** [jopeek/fvtt-loot-sheet-npc-5e#331]
I think the line here needs to use CurrencyHelper.... instead of this....

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/388bb49d5e4f303a784c3ac9a62a3c7b0f745b8f/src/modules/classes/LootProcessor.js#L342

**Comment by DanielBoettner** [comment]
Thanks for reporting.
This should be fixed by #342
