### ISSUE TITLE
Indirectly able to make PCs lootable - Lose character info

### ISSUE THREAD

**Issue by AvDalfsen** [jopeek/fvtt-loot-sheet-npc-5e#335]
**Describe the bug**
Shortly before having to call the session I selected a number of NPCs and PCs to put them on the combat tracker. By accident I clicked on the 'make lootable' icon, which made _everything_ I had selected lootable, including the PCs. After deleting those PC tokens and adding them back from the token list, they were no longer lootable, but they also didn't have their features and spells anymore.

**To Reproduce**
1. Add NPC and PC to the scene.
2. Select both of them.
3. Right click on the NPC.
4. Click 'Make lootable'.
5. See that PC is now lootable, too.
6. Delete PC's token and add it back to the scene.
7. PC is no longer lootable, but also has no features and spells.

**Expected behavior**
I was honestly unaware of the icon to begin with, so it was a surprise, but I'd expect it to detect whether or not you have PCs selected and change its behaviour based on that.

**Screenshots**
(The top 4 tokens are PCs)
![Untitled](https://user-images.githubusercontent.com/42408840/165176382-46ff22b9-d7a3-43de-9d11-c2909529eda9.png)

**Comment by DanielBoettner** [comment]
I will add fixes for that, thanks for reporting.
