### ISSUE TITLE
Adjust buy/sell prices

### ISSUE THREAD

**Issue by WH17EW0LF** [jopeek/fvtt-loot-sheet-npc-5e#337]
**Is your feature request related to a problem? Please describe.**
I would like it to be made possible to adjust the buy and the sell prices of items individually. As I can see now, you adjust both prices with the same scaling.

**Describe the solution you'd like**
Seperate buy/sell price options

**Comment by DanielBoettner** [comment]
Will have to think about this.

Adding a second slider could be enough.
But if this is updated it could be done more general.

And either way it will have to get implemented into
the currency handling. Which I did not manage to really simplify.

**Comment by DanielBoettner** [comment]
Thanks for the feedback. Will take this into account when I get to it.
