### ISSUE TITLE
When I buy from a merchant I get platinum.

### ISSUE THREAD

**Issue by Altrix1** [jopeek/fvtt-loot-sheet-npc-5e#339]
When I buy from a merchant I get platinum.
![Zrzut ekranu 2022-05-14 131307](https://user-images.githubusercontent.com/86872105/168423500-b201dda4-71a0-483c-ac88-99efb09723ce.png)
![Zrzut ekranu 2022-05-14 131351](https://user-images.githubusercontent.com/86872105/168423503-3882119d-6460-416b-8ed2-a92676c755b2.png)

**Comment by TheFinalPerry** [comment]
I am getting the same issue.

**Comment by DanielBoettner** [comment]
I Will take a look into currency conversion again.
