### ISSUE TITLE
[Feature Request] Make an item unlootable

### ISSUE THREAD

**Issue by HTalarmo** [jopeek/fvtt-loot-sheet-npc-5e#340]
**Is your feature request related to a problem? Please describe.**
The way Foundry deals with creature attacks is that you basically have to put the attack into the creature's inventory as a weapon, and you can then use that weapon to attack. However, many of these attacks especially at higher CRs are obviously not meant to be actual items that the players will loot from the creature. Take [Assassin](https://www.dndbeyond.com/monsters/16790-assassin), for example. It has an attack with the shortsword that has an additional constitution save attached for extra poison damage. Clearly the assassin is meant to just be wielding a regular shortsword, and the extra poison damage is just an ability that the assassin adds on top of the regular weapon damage. However if you add that attack into the creature's inventory as a weapon, the players can now loot that weapon, and that may be very much undesirable for the GM.

**Describe the solution you'd like**
 The simple solution would be to just have a checkbox attached to each weapon's details page that makes the weapon unlootable. So when the creature is converted into a loot sheet, the item doesn't show up on the item list just like how its features don't appear there. A more involved solution could be to convert the item into the more appropriate version. Like in the case of the assassin, the attack instead converts into a regular shortsword. However I imagine that would be a much more complicated feature in scope.  

**Describe alternatives you've considered**
Currently I've been using two methods to get around this. First is to just change the OP weapon's type to a natural weapon, since the loot sheet does have an option to filter out natural weapons when it does the conversion. This effectively does the above, but it feels a little clunky. This is also why the solution should be relatively simple to implement since it can just check for the checkbox value while it's filtering out natural weapons. The second way is to have that special attack as a feature on the creature instead. However, this also feels a bit clunky since that's not really how Foundry expects you to do creature attacks, as is evident from the fact that that's not how most attacks are defined in the 5e module compendiums. 

Cheers.

**Comment by DanielBoettner** [comment]
Hey @HTalarmo thanks alot for the issue.
Will think about (if) how and when to implement that.

**Comment by DanielBoettner** [comment]
I dont't know if this is an option for you. But a quickfix could be **to set weapons weapon type to "natural weapon"**.
As the module should filter these out as well.
