### ISSUE TITLE
Keeps Updating, remains at version  3.5.10

### ISSUE THREAD

**Issue by Resfelm** [jopeek/fvtt-loot-sheet-npc-5e#343]
Regardless if I hit "Update All" or if I uninstall and enter the manifest URL manually, the module updates but remains at version 3.5.10.

**Comment by Ameranth** [comment]
Yes I have this same issue, I believe this is because `module.json` is still referencing the download link for `v3.5.10`.

Line 84 in `module.json`:
`"download": "https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/download/v3.5.10/lootsheetnpc5e.zip"`

**Comment by DanielBoettner** [comment]
Thanks for reporting.
I push a fix ASAP
