### ISSUE TITLE
Most recent update broke all loot sheets

### ISSUE THREAD

**Issue by CharlesHunter** [jopeek/fvtt-loot-sheet-npc-5e#346]
**Describe the bug**
After updating, players can no longer loot from loot sheets.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: lootsheetnpc5e]
    at Function._getPriceModifier (TradeHelper.js:354:35)
    at Function._prepareTrade (TradeHelper.js:316:36)
    at Function._handleTradyByType (TradeHelper.js:270:34)
    at Function.tradeItems (TradeHelper.js:40:18)
    at o.handleRequest (SocketListener.js:90:39)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getEmbeddedDocument')
[Detected 1 package: lootsheetnpc5e]
    at Function.moveItemsToDestination (ItemHelper.js:77:39)
    at Function.lootItems (TradeHelper.js:57:43)
    at o.handleRequest (SocketListener.js:99:39)

**To Reproduce**
1. Log in as a player.
2. Open a loot sheet that you have permission to loot.
3. Attempt to loot.

**Expected behavior**
The item should move from the loot sheet inventory to my inventory.

**Comment by DanielBoettner** [comment]
Sorry for the inconvenience. 
I had to update (or more honestly, fix) how the flags where saved. I suppose that may have broke some sheets.

As a GM please try updating these sheets before players again interact with them.
"Updating" just means doing the settings again. Like the price modifier, the sheet type and permissions.
 
I could go into details but that wont help you much. If you can please feel free to send me exports of 1-2 sheets that have this issue for your players. I could try to compare these "old" actors with current ones and maybe I can create a macro or a migration script.
