### ISSUE TITLE
CHat log shows wrong price for Buy Item

### ISSUE THREAD

**Issue by Terrox** [jopeek/fvtt-loot-sheet-npc-5e#348]
**Describe the bug**
The chat log reports the original item price rather than the cacluated sale price if it's changed from the default 100%

**To Reproduce**
Set merchant price ratio to 120%
Buy Item
Check chat log

**Expected behavior**
Price should match price player paid. In my example it should be 30.25 but is 25

<img width="1270" alt="Screen Shot 2022-06-10 at 6 27 25 pm" src="https://user-images.githubusercontent.com/16533005/173024496-e5dfbe48-b52c-4d7e-8cf3-496a2fbc1a27.png">

**Comment by Terrox** [comment]
really cool. though default price seems to set at 1 for existing actors.

**Comment by DanielBoettner** [comment]
I have more bugfixes in the pipeline.
But it will take some days till I can merge it. 
Sorry for the delay.
