### ISSUE TITLE
some bugs in App and updates

### ISSUE THREAD

**Issue by rinnocenti** [jopeek/fvtt-loot-sheet-npc-5e#351]
**Describe the bug**
I just updated and encountered some issues.
the price adjustment values I had on my merchants are not updated for the new version.
My actors and tokens have "null" values, which appears zero in the panel.
Which forces me to manually update the values on all my actors (which in my case are more than 300) so it's not viable.
A macro would be nice to help with this update.

another thing, even if you do the updates by hand there is another problem.
![image](https://user-images.githubusercontent.com/3178127/173260960-d8292a5a-da83-49dd-b48d-962cb86117cd.png)
reading the window is impossible, it's probably some problem with the rendering in the foundry app.

Another thing is that if I try to change an actor, without him being in a scene, the change fails and gives me an error.
![image](https://user-images.githubusercontent.com/3178127/173261051-ad46751a-f3d8-4a5f-a85e-33b6c9baf3c6.png)
and no matter what I type it doesn't update (besides losing my configuration before the update)

however if I put a token of that actor in the scene, I can make both the change in the token and in the actor.
(which is a problem because in addition to having to do it manually, I still have to put them in the scene)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser App Foundry
 - Version v9.269

**Comment by DanielBoettner** [comment]
Thanks for the reports, will look into it.
