### ISSUE TITLE
Merchant mode NPCs now think prices are entered as copper

### ISSUE THREAD

**Issue by bkis1** [jopeek/fvtt-loot-sheet-npc-5e#360]
After the last update of loot sheet (of note I also updated 5e ruleset at the same time)...merchants now list prices as if the item price has been set in copper.  For example the item listed price is 1000, it now sells for 10 GP from the merchant.
I am hosted on the Forge.

**To Reproduce**
Open merchant, note the incredible sale they are having currently ;)

**Expected behavior**
Unit prices continue to be converted 1:1 for selling price...as in 1000 price sells for 1000 gp.

**Screenshots**
See attached screenshot.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

**Comment by DanielBoettner** [comment]
Should be fixed in the next release.
You can manually fix it by adjusting the price modifier to **100**
