### ISSUE TITLE
Currency can't fully be negated. 

### ISSUE THREAD

**Issue by rprejean** [jopeek/fvtt-loot-sheet-npc-5e#361]
**Describe the bug**
Can not auto seed creatures without currency. LS wants to add coin.

**To Reproduce**
1. Go to creature loot sheet and set the currency to 0 or any resulting die like 0d0[cp] or 1d0[cp]
2. Drag new creature to play field.
3. Currency defaults to 1 cp

**Expected behavior**
Place creatures that don't carry money, typically beasts.

**Screenshots**
![image](https://user-images.githubusercontent.com/4765489/174469142-91b50808-3651-492b-8e07-ce616a438fbe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 102.0.5005.115 (Official Build) (64-bit)

**Additional context**

**Comment by DanielBoettner** [comment]
Thanks for the issue. I will fix this along with the other bugfixes and some minor features.
Will still take some days, but I hope until the weekend I can release the next version.
