### ISSUE TITLE
Unable to see item image in merchant menu.

### ISSUE THREAD

**Issue by MsVella** [jopeek/fvtt-loot-sheet-npc-5e#363]
**Describe the bug**
Item images don't seem to be appearing in the trade or inventory menu, and I am unable to trade.

**To Reproduce**
1. Install mod as normal
2. Configure token to merchant state and drag items into their inventory
3. Observe error where item images are invisible

**Expected behavior**
I would expect the images to appear like in other videos I've watched of the module in action, and pictures I've seen of it.

**Screenshots**
![noimage](https://user-images.githubusercontent.com/88259742/174940173-dd91ed66-9293-4c2f-90cc-6f33e4f1e147.PNG)

**Desktop [(please](url) complete the following information):**
 - OS: Windows 7
 - Browser Chrome / NA
 - Version Latest (3.6.0)

**Additional context**
Edit: confirmed to also happen when I have just this module active!

Edit 2: seems like it's only happening with local images, not core ones?

**Comment by DanielBoettner** [comment]
> Edit 2: seems like it's only happening with local images, not core ones?

I suspect that the uploaded image have permission or path issues.
I also do not know if windows 7 still has the latest chrome version(s).

Could you check with the chrome developer console on what the **paths** of the images is in that place?
