### ISSUE TITLE
Natural Weapons Missing

### ISSUE THREAD

**Issue by kristinamitkov** [jopeek/fvtt-loot-sheet-npc-5e#365]
**Describe the bug**
Weapons of weapon type "Natural" do not appear in the merchant's weapon list.

**To Reproduce**
1. Go to the merchant's inventory
2. Drag a weapons of weapon type "Natural" (for example an Orb of the dnd5e Items (SRD) Compendium)
3. See error

**Expected behavior**
Weapons of weapon type "Natural" should appear in the merchant's weapon list.

**Additional context**
Adding an existing weapons of another weapon type, then editing it from the merchant's inventory and changing its weapon type to "Natural" will make it disappear too.

**Comment by jopeek** [comment]
What natural weapons are you looking to sell at your merchant…..?

**Comment by kristinamitkov** [comment]
One example would be the "Orb", which is listed as a "Natural" weapon in the dnd5e Items Compendium.

**Comment by DanielBoettner** [comment]
Would you have a link to SRD content or any other sources?
 
 Could find these information on any of these:
 [Orb | roll20](https://roll20.net/compendium/dnd5e/Orb#content)
 [Orb | dndbeyond](https://www.dndbeyond.com/equipment/orb)

I think we could change the filter for the merchant. So it also shows natural weapons.
Have to take a look in which places (like looting) we filter out the natural weapons.
