### ISSUE TITLE
entity.js import fails when running foundry with non-default route prefix

### ISSUE THREAD

**Issue by proarunas** [jopeek/fvtt-loot-sheet-npc-5e#368]
**Describe the bug**
References to "entity.js" use absolute paths. When the foundry is configured to use route prefixes, the imports fail.
References to "npcs.js" already use relative paths, so the same fix should be applied to "entity.js" imports.

**To Reproduce**
1. Edit foundry options to use some route prefix in "Data/Config/options.json".
2. Launch a world that has LooSheetNpc5e enabled.
3. Check the browser console to see that it can't find the entity.js.

**Expected behavior**
The module should work with non-default prefixes.

**Comment by mkemp** [comment]
Running into the same issue. When looking at the source in the browser for `lootsheetnpc5e.js`:

```js
import e from "../../systems/dnd5e/module/actor/sheets/npc.js";
import t from "../../../../../../systems/dnd5e/module/item/entity.js";
```

If I manually fix the installed module to the following everything works as expected:
```js
import e from "../../systems/dnd5e/module/actor/sheets/npc.js";
import t from "../../systems/dnd5e/module/item/entity.js";
```

**Comment by proarunas** [comment]
That was my initial fix as well. (it's for `Data/modules/lootsheetnpc5e/lootsheetnpc5e.json` if anyone else is wondering.)

Added a pull request for the build to generate the file that way, to begin with.
