### ISSUE TITLE
cannot open character sheet

### ISSUE THREAD

**Issue by Terrox** [jopeek/fvtt-loot-sheet-npc-5e#370]
**Describe the bug**
I can no longer open the character sheet of a loot type character.

**To Reproduce**
unknown

**Expected behavior**
Open as normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version latest public

**Additional context**

TypeError: r is undefined
[Detected 1 package: lootsheetnpc5e]
    _playerPermissions LootsheetNPC5e.js:356
    _prepareGMSettings LootsheetNPC5e.js:309
    getData LootsheetNPC5e.js:91

-

TypeError: r is undefined
[Detected 4 packages: lootsheetnpc5e, lib-wrapper, item-piles, monks-active-tiles]
    _playerPermissions LootsheetNPC5e.js:356
    _prepareGMSettings LootsheetNPC5e.js:309
    getData LootsheetNPC5e.js:91
    _render foundry.js:3062
    _render foundry.js:3764
    render foundry.js:3021
    render foundry.js:4259
    render LootsheetNPC5e.js:139
    _onClickDocumentName foundry.js:47609
    call_wrapped libWrapper-wrapper.js:511
    registerLibwrappers libwrapper.js:29
    checkClickDocumentName monks-active-tiles.js:6905
    _onClickDocumentName#0 libWrapper-wrapper.js:187
    call_wrapped libWrapper-wrapper.js:511
    clickDocumentName monks-active-tiles.js:6853
    _onClickDocumentName#0 libWrapper-wrapper.js:187
    jQuery 2

**Comment by mkemp** [comment]
I suspect e this is related to https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/368.

**Comment by Terrox** [comment]
my foundry is on a root path like http://xx.example.com:30000/
non-ssl though

**Comment by Terrox** [comment]
might be related to null currency https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/375
