### ISSUE TITLE
Not compatible with DnD5e v2.0+

### ISSUE THREAD

**Issue by glitchies** [jopeek/fvtt-loot-sheet-npc-5e#378]
There  has been a restructuring of DnD5e's Project Structure and has broken a lot of links and locations.

The *.js & *.html extensions have been renamed.

Importing of 5e is no longer required.

**Comment by jopeek** [comment]
Yeah this module is currently not V10 compatible and consequently not compatible with dnd5e 2+.On Sep 9, 2022, at 10:45 AM, glitchies ***@***.***> wrote:﻿
There  has been a restructuring of DnD5e's Project Structure and has broken a lot of links and locations.
The *.js & *.html extensions have been renamed.
Importing of 5e is no longer required.

**Comment by xxUltiMoxx** [comment]
are there any plans to make the module v10 compatible in the future?
