### ISSUE TITLE
Lootsheet Isn't Applicable in Game

### ISSUE THREAD

**Issue by Brethraeus** [jopeek/fvtt-loot-sheet-npc-5e#382]
**Describe the bug**
Using your Product in Foundry VTT (LootSheetNPC5e) there is no function (once the module is activated to turn an NPC into a Lootsheet as either Loot or a General Vendor. Nor is there any other properties showing up, other than just appearing in the module list that the module is actually in Foundry itself. Don't know if this is a glitch or not. So I uninstalled and reinstalled the Module and came back to the same issue. Dont know if it's happening for anyone else, but this was going to be a great asset for most of my games so i didnt have to stop and provide a list of what the vendors had/didnt have or what the corpses had on them. they could just grab in their own time and go. 

**To Reproduce**
1. Go to 'Actor Selection'
2. Click on 'new Actor'
3. Scroll down to 'N/A'
4. Once actor is created, from the sheet type drop down menu, where in v9 the LootSheet once was listed, it is no more.

**Expected behavior**
A way to turn an Actor/Object into a Lootable object/vendor.

**Screenshots**
[https://imgur.com/pnSmShE](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 105.0.5195.127

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jopeek** [comment]
FoundryVTT v10 is not supported at this time. I am working on a version that will work, but it’s not ready for release yet as the self serve functionality isn’t working yet.

**Comment by Brethraeus** [comment]
cool thanks. it shows it was up-to-date via the module update list so it was just confusing to me. thanks for the heads up though. hope to have it as soon as it drops. was a great module to work with.

**Comment by jopeek** [comment]
That’s weird. Definitely shouldn’t say that…

**Comment by Android8675** [comment]
Doesn't for me, still says v9.269. Looking forward to v10 release. Ok to pull in v10 build for testing with the usual caveats?

**Comment by jopeek** [comment]
There’s a Lootsheet Simple (or similar name) branch that partially works in v10. The main part not functioning there is the actual purchase and loot functions. In my game I drag items to the players when they want something. As a workaround.

**Comment by HippyCraig** [comment]
Not sure if this is related but thought it would help, on reloading the page at the top of the console I found the following.  I didnt notice it right away as first two items in the cleared out console but the loading of foundry pushes these out of view.

![image](https://user-images.githubusercontent.com/17074456/196011752-d389955b-2d3d-4d1d-b5c5-bb3d4c9e467d.png)

**Comment by jopeek** [comment]
It’s part of it but even if i change that, you’ll maybe see the sheet but it’ll be very broken.
Sent with Spark

**Comment by sbminer123** [comment]
Hey, hows the progress going, excited to use this :)

**Comment by Axblade** [comment]
Any Updates?

**Comment by jopeek** [comment]
Please try the beta release at https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/4.1.1-beta

**Comment by grepheavy** [comment]
> Please try the beta release at https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/4.1.1-beta

I installed the module, doesnt even give me the option to change to this type of character sheet with any character.  tried installing both from download and from link in setup. not working, am i missing something?

**Comment by Mellowub** [comment]
> > Please try the beta release at https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/4.1.1-beta
> 
> I installed the module, doesnt even give me the option to change to this type of character sheet with any character. tried installing both from download and from link in setup. not working, am i missing something?

Instead of getting this, I'm able to change the sheet, but no actors can access it because I have to make the NPC under the actor tab be observable, rather than being able to doing it on the character sheet which makes it a lot easier for different kinds of NPCs. hopin the whole thing gets updated cause the simple one is tough to use D:
