### ISSUE TITLE
Split coins for Observer

### ISSUE THREAD

**Issue by rinnocenti** [jopeek/fvtt-loot-sheet-npc-5e#39]
allow the option to split coins for observer permission, as I don't want the player to be able to edit the item within the loot / merchant with permission from the owner.

**Comment by tonyrobots** [comment]
Came here to ask for exactly the same thing. Could take a stab at it and do a pull request too. Basically need a permission level (the default?) that means the loot belongs to the party, but they can't change it; they can only take items and currency, including the auto-split.
