### ISSUE TITLE
GM Permissions and GM Coin Distribution Sections of Loot Sheet Not Shown

### ISSUE THREAD

**Issue by Drakynn** [jopeek/fvtt-loot-sheet-npc-5e#390]
**Describe the bug**
When creating a "loot" npc, the normal GM sections where you can assign permissions and split the coin among players do not appear.  GM is not able to determine who gets loot share or control access to loot sheet.

Players are able to click the diamond and loot all of the coin or take individual items from a loot sheet.  

Players are able to purchase items from a merchant sheet.

**To Reproduce**
1. Create an NPC character.
2. Set the sheet to dnd5e.LootSheet5eNPC
3. In GM Settings, type of sheet is set to "Loot" by default.

**Expected behavior**
Expect to see interface as documented in multiple screenshots in README.md

**Screenshots**
*Expected view*
<img width="241" alt="lootsheetA" src="https://user-images.githubusercontent.com/76929992/218292598-44e50ba4-8acc-4c2a-93e7-9a7ddac5653c.png">

*Actual view - no permissions, no coin distribution*
<img width="276" alt="lootsheetB" src="https://user-images.githubusercontent.com/76929992/218292619-e107188b-f3f2-4784-b8a5-ae798dd237ae.png">

**Desktop (please complete the following information):**
 - OS: Win 11 and MacOS 13.1
 - Browser: Latest Chrome and Firefox

**Notes**
Duplicate of part of what was reported in Issue #387 , however I'm not having any problems from player perspective.

Many console deprecation warnings, but no errors reported.

**Comment by jopeek** [comment]
That function is not available anymore. You can use the regular permissions screen to grant access. I need to update the readme to remove those references.

**Comment by Drakynn** [comment]
What about the coin share option?

**Comment by jopeek** [comment]
Also not available. I may bring that back but not sure yet. Was a giant pain to make purchases and transactions work in the first place. Unfortunately, the dnd5e system changes its internal workings so frequently, it’s been hard to keep up with, so I’ve had to focus on the bare basics.

**Comment by Drakynn** [comment]
Permissions is an easy adjustment to make, but the coin split is a popular feature and reason many people use(d) this module.

I was able to find a coin split macro and update it to the current 5e schema where it's using actor.system.currency.pp.  It's not as elegant as your solution but it works.
