### ISSUE TITLE
Not Working on all NPC's in 5e

### ISSUE THREAD

**Issue by SilverwolfNL** [jopeek/fvtt-loot-sheet-npc-5e#391]
**Describe the bug**
Somehow on soe monsters/npc if i select loot sheet.  Then i cant open characters sheet anymore of that monster

**To Reproduce**
1. Opened charcter sheet
2. changed sheet to loot sheet
3. shete closes and then unable to open sheet anymore need to redrag token to sheet. had that woith severall mosnters mopt sure what made those different from the rest.

**Expected behavior**
Expected tp be able to open char sheet again and not have to delete token and readd

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 11
 - Browser [e.g. chrome, safari]: edge

**Smartphone (please complete the following information):**

**Additional context**
Add any other context
[fvtt-Actor-keresta-delvingstone-(copy).zip](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/files/10725522/fvtt-Actor-keresta-delvingstone-.copy.zip)
attached oen of monsters i had issue with

**Comment by ghost** [comment]
I ran into this issue when also using module Inventory+. Looks like they do not play nicely together.

**Comment by SilverwolfNL** [comment]
Hmm not using that module myself , weird thing only had that with specific NPC … not sure why .
