### ISSUE TITLE
failed to install due to http://localhost:30000/worlds/porvenir/art/porvenir-banner.jpg 404 (Not Found)

### ISSUE THREAD

**Issue by brandf** [jopeek/fvtt-loot-sheet-npc-5e#392]
**Describe the bug**
<img width="966" alt="image" src="https://user-images.githubusercontent.com/877443/223911835-53c1494a-ba36-4fde-8260-a42ee725b71e.png">

**To Reproduce**
1. on the latest Foundry click install on this package
2. see error

**Comment by jopeek** [comment]
The compatibility warnings are just warnings and not all for lootsheet. It’s still installed. Also not related to the Porvenir error. That’s just a missing image for one of your worlds.
