### ISSUE TITLE
Errors when changing to Loot Sheet Simple

### ISSUE THREAD

**Issue by HippyCraig** [jopeek/fvtt-loot-sheet-npc-5e#394]
**Describe the bug**

**To Reproduce**
Create a new NPC no custimizations, no token assigned other than the default mystry man
Change sheet to loot
Cant open character sheet any more

**Expected behavior**
Sheet to appear looking like the loot sheet

**Screenshots**
First Insatlling the module from the main window doesnt change to gray after installation I assume thats becuase the name doesnt match the listing.  New name shows Loot Sheet NPC 5e (Simple Version) as you can see the install in the Install Module is not grayed out even though its installed, other than the display name diff.
![image](https://user-images.githubusercontent.com/17074456/226114442-10cef394-7b89-4ec4-997d-8b1689c722bc.png)

When added to a sheet I get the following error in the console, not sure if this is related to the mystry man icon as there seems to be a ref to Default_Token Not set
![image](https://user-images.githubusercontent.com/17074456/226114388-670e8e8b-8b97-47e7-b0e3-9f8b15fe3c0d.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome 
 - Version 111.0.5563.65 (Official Build) (64-bit)

**Additional context**

**Comment by jopeek** [comment]
What foundry version and what version of dnd5e?

**Comment by HippyCraig** [comment]
Sorry forgot to add that 
5e - 2.1.5
Foundry v10.291


I also noticed now when I go back in for some reason all the NPC are stuck with the loot sheet and I cant open them anymore, its just a test game so its not impacting me, but thought it was worth mentioning.  Even the ones with Proper tokens images wont open here are the errors Im seeing now:

This is from opening an NPC on the canvas nothing open but this is in hte console
![image](https://user-images.githubusercontent.com/17074456/226114754-e3682370-fe20-43ee-af5b-8a49e296a609.png)
and sometimes this
![image](https://user-images.githubusercontent.com/17074456/226114924-c6188c87-2c3d-470e-a20e-8af5ba7047c3.png)

**Comment by jopeek** [comment]
Very odd. I tested this in a clean game and didn’t have any of those issues. I’m running my weekly game today so I’ll have a look. If I can reproduce it, I can fix it.

**Comment by jopeek** [comment]
The first part, about the module not appearing in grey in the installer is not something I'm going to try to fix. I'm not sure how Foundry determines that and anything I try to do will likely just cause problems for people using the older version. It's likely related to the fact that I used the same package for this new version but I didn't feel like going through submitting a new package entirely to foundry...

**Comment by jopeek** [comment]
Tracked down the bug you experienced and fixed it in 5.0.5. Was related to it attempting to display spells after changing an NPC to the loot sheet type. I've ensured that spells don't appear anymore. Should help. Open a new ticket if you get any further errors. The screenshots and line numbers in particular helped me track this down. Thanks!

**Comment by HippyCraig** [comment]
Thanks everything is working again!!!
