### ISSUE TITLE
FoundryVTT v11 - Unsupported Core Version

### ISSUE THREAD

**Issue by nickkeane** [jopeek/fvtt-loot-sheet-npc-5e#396]
Needs an update for FVTT version 11

**Comment by Drakynn** [comment]
Attempting to install on FVTT Ver 11 yields the following error.

![image](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/76929992/8ad850b2-0d32-49d5-a9fd-a1340cca74c6)

![image](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/76929992/e0f26663-5e79-4fa6-b15b-d241bfcb5411)
