### ISSUE TITLE
Problems with some thumbnail images on items

### ISSUE THREAD

**Issue by Fridan99** [jopeek/fvtt-loot-sheet-npc-5e#397]
**Describe the bug**
Some item's thumbnails images doen'st appear in the loot sheet, I suspect that image routes/path that include a % are not detected by the loot sheet. 

**To Reproduce**
1. Create an item with a thumbnail image path that includes a % simbol
2. Open the loot sheet from an npc

**Foundry version and System**
Foundry v10.291
System dnd5e 2.2.1
Loot Sheet 5e 5.0.6 (latest version)

**Expected behavior**

**Screenshots**

The thumbnail image of the item appears as normal (Tidy5e sheet)
![1 1](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/86131373/91fd6121-2a9a-491f-81f5-d5081e0e6ad2)

The thumnail image of the item is missing (lootsheet 5e sheet)
![1 11](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/86131373/9eb6cea7-aa73-440a-b1fa-591ff266c9fe)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [chrome] and Foundry app itself
 - Version [114.0.5735.134 (Build oficial) (64 bits)]

**Additional context**

There seems to be a problem with the item's thumbnails images on the loot sheet.

I've only had this happen with items from the wanderer's guide to merchants & magic module. I noticed that all the paths of that module for the image have the % character, maybe that's it... with the rest of the sheets (default, tidy5e...) the thumbnail of the item appears correctly. 

**example of data path**: modules/wanderers-guide-2-merchants-n-magic/Magic%20Items%20(Art)/Arctic%20Ring.webp

**Comment by jopeek** [comment]
I’ll see if I can replicate this with an image with the % character in it.

**Comment by Fridan99** [comment]
ok, let me know if you need anything

**Comment by jopeek** [comment]
Does the image show up fine in the default sheet? Lootsheet isn’t doing anything special with the items and their images.

**Comment by Fridan99** [comment]
Yes, it works in the default sheet. I am observing that these are HTML type images.

Default sheet
![1 1](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/86131373/2b0e1627-2c45-43a0-95a9-1e5fd1a0bb36)

Loot sheet
![1 12](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/86131373/15da2deb-6132-452e-bd7c-388b9dc87f9e)

**Comment by jopeek** [comment]
How would I get those items? They’re not in the SRD compendium.

**Comment by Fridan99** [comment]
i sent you to your gmail some items that reflect the problem.

**Comment by jopeek** [comment]
Thanks, I’ll take a look later this week.
