### ISSUE TITLE
[Feature Request] Question about size box text of biography

### ISSUE THREAD

**Issue by Fridan99** [jopeek/fvtt-loot-sheet-npc-5e#398]
**Is your feature request related to a problem? Please describe.** not at all
A question: Is it intentional that only half of the biography text box is visible or is it some kind of bug? I have seen that the whole page is not used. 

**Describe the solution you'd like**
Probably displaying more of the text box would be nice, rather than just half of the sheet. 

**Img**
In this picture, the biography image is cut off, as the text box only uses half of the sheet to display the biography content, even if I scroll down or up, the image cannot be seen in its entirety.
![1 1](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/86131373/e403b8a1-27c0-433e-8da5-4e43ddea0c6b)

**Foundry version and System**
Foundry v10.291
System dnd5e 2.2.1
Loot Sheet 5e 5.0.6 (latest version)

**Comment by jopeek** [comment]
Seems like a bug :) will look at it in about two weeks when I’m back from vacation.
