### ISSUE TITLE
failure to install 

### ISSUE THREAD

**Issue by Birdwin14** [jopeek/fvtt-loot-sheet-npc-5e#399]
**Describe the bug**
refusing to install due to unable to load verified module

**To Reproduce**
attempt to install
See error

**Expected behavior**
i want to install and use 

**Screenshots**
![Screenshot 2023-07-09 165544](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/139078418/55e9964b-62d1-4a32-bf76-d663f6e0b02a)

**Desktop (please complete the following information):**
 - OS: windows
 - Foundry
 - Version 11

**Comment by jopeek** [comment]
Foundry V11 is not yet supported.

**Comment by Birdwin14** [comment]
my bad
