### ISSUE TITLE
Add PF1e compatibility

### ISSUE THREAD

**Issue by mistamichal** [jopeek/fvtt-loot-sheet-npc-5e#4]
If you could make the mod pf1 compatible that would be great, cheers.

**Comment by SvenWerlen** [comment]
For your information, I forked the module and adapted it for pf1. I also added support for translations (currently: en/fr). https://github.com/SvenWerlen/fvtt-loot-sheet-npc-pf1

**Comment by mistamichal** [comment]
Nice one.

**Comment by jopeek** [comment]
That’s great, thank you!
