### ISSUE TITLE
Module not showing up

### ISSUE THREAD

**Issue by arcanjl** [jopeek/fvtt-loot-sheet-npc-5e#401]
Pretty sure it’s something silly. I’m doing. I install it and it doesn’t show up in the module list.

**Comment by jopeek** [comment]
Any errors in the dev console that might be related?

**Comment by arcanjl** [comment]
Duh. I’ll look. Ty.

Sent from my iPhone

On Jul 11, 2023, at 3:30 PM, Jan Ole Peek ***@***.***> wrote:

﻿

Any errors in the dev console that might be related?

**Comment by arcanjl** [comment]
I looked I am getting errors, but nothing specific to LootSheet.

**Comment by jopeek** [comment]
Can you try it in a world without other modules enabled? Also what version of foundry and of the lootsheet? I just tested it with 11.305 on the weekend.

**Comment by arcanjl** [comment]
I am still on 10, I was about to try find the culprit

**Comment by jopeek** [comment]
For 10, make sure you’re NOT in lootsheet 11.X but rather on 1.X or whatever. The latest version should not have been updated to on foundryv10

**Comment by arcanjl** [comment]
Ok, that's it. 
TY

**Comment by jopeek** [comment]
Strange that foundry allowed you to update…

**Comment by arcanjl** [comment]
I just installed it from searching, you think that could have been it?

**Comment by jopeek** [comment]
I think this was my fault. I had the minimum version set to 10 instead of 11. I am surprised it didn’t work in 10, but obviously I updated something that made it not work in 10 anymore. You should use version 5.X and that’ll be ok then. If you uninstall and search again, hopefully it offers 5.x

**Comment by arcanjl** [comment]
Ok, will do. TYVM! Do you know if the permissions that was recently fixed will work in that version?

**Comment by jopeek** [comment]
No, that was only in v11.

**Comment by arcanjl** [comment]
Ok, I will wait, it shouldn't be much longer before I make the plunge. TYVM
