### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [jopeek/fvtt-loot-sheet-npc-5e#402]
I hear so many good things about this module but can not find any documentation or helps anywhere on how to use it. I think, from the sparse information I have found that you have to create an NPC in order to assign a sheet to it. Where is there some concise and detailed help?

**Comment by jopeek** [comment]
The readme file has some help but yes, you create an NPC, drag a token to the map and change its sheet type to lootsheet, choose between loot and merchant and give it items to purchase/loot. That’s it.
