### ISSUE TITLE
Changing permissions resets the sheet

### ISSUE THREAD

**Issue by Seledrex** [jopeek/fvtt-loot-sheet-npc-5e#404]
**Describe the bug**
When changing the permissions of the sheet, the sheet resets to its default state. All items added to the sheet are removed, and the type is set back to Loot. Additionally, none of the players are shown in the Permissions anymore until the sheet is closed and reopened.

**To Reproduce**
1. Create a NPC token
2. Open the sheet and set the sheet configuration to loot sheet NPC
3. Change type to Merchant
4. Add items to sheet
5. Change permissions
6. Sheet gets reset

**Expected behavior**
Changing permissions does not reset the sheet.

**Screenshots**

![Animation](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/22948330/9657b2f0-5e50-40f7-b0ef-4e56b42993cd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Foundry VTT 11.306
 - FVTT Loot Sheet NPC 11.222.1

**Comment by jopeek** [comment]
Strange. I haven’t noticed that myself but I will test that out this weekend.

**Comment by Seledrex** [comment]
Thanks that would be great!

**Comment by jopeek** [comment]
Yeah confirmed. Very strange. Not quite sure if a fix yet but I’ll spend some time. Worksround is to set up the sheet with all the items first, then do the permissions.

**Comment by Seledrex** [comment]
> Yeah confirmed. Very strange. Not quite sure if a fix yet but I’ll spend some time. Worksround is to set up the sheet with all the items first, then do the permissions.

Thanks for having a look, and thanks for the workaround. Looking forward to a fix if possible!

**Comment by jopeek** [comment]
Simply refreshing the browser also seems to fix it.
