### ISSUE TITLE
No Loot Sheet Option (multiple games)

### ISSUE THREAD

**Issue by Shayulghul** [jopeek/fvtt-loot-sheet-npc-5e#405]
**Describe the bug**
I no longer have the option to choose Loot Sheet for an NPC. I recently reinstalled it, and the option just isn't there. I did recently update to D&D5e 2.3.0, so I'm not sure whether that created the issue.

I tested this in multiple games (one normal game, one test game with no other modules installed).

**To Reproduce**
1. Install Loot Sheet NPC 5e
2. Create a new NPC actor.
3. Click the Sheet button.
4. Click the This Sheet menu.

**Expected behavior**
The sheet should be an option.

**Screenshots**

![Screenshot 2023-08-11 at 3 25 12 AM](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/81927456/5244eed4-bbf1-469c-a007-8ce627d8c4c6)

- Foundry 10.303
- Browser: Version 115.0.5790.170 (Official Build) (x86_64)
- D&D 5e: 2.3.0
- Host: The Forge

**Comment by jopeek** [comment]
Make sure you updated lootsheet to 11.230.1 and you may have to reenable it in the modules settings.

**Comment by mfozz** [comment]
Hmm, the latest version of the module I see is 3.6.1. I had just recently installed it to test it. I did just realize that the latest supported version is 9.269, so I'll try a different option. Sorry for the bother

**Comment by jopeek** [comment]
There’s a new version called lootsheet-simple. You’ll want to remove that old 3.6.1. Here’s a link to the recent release. https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/11.230.1

**Comment by mfozz** [comment]
Ohhhhh, I misunderstood. Thanks! I'll test it out. Love the loot sheet.

**Comment by Shayulghul** [comment]
Just an update: I read in another thread that v5.0.6 and earlier works in v10, so I reverted it until I can upgrade my games to v11. This combo seems to be working great at the moment.
