### ISSUE TITLE
This stopped working

### ISSUE THREAD

**Issue by BBendriss** [jopeek/fvtt-loot-sheet-npc-5e#406]
Loot Sheet for D&D 5E games has stopped working. No longer an option to select this sheet, and existing vendors from last weeks game have become default D&D NPC sheets. No longer an option to choose this module inside the game either. Something broke.

**Comment by jopeek** [comment]
Make sure you’re on dnd5e 2.3.0 and lootsheet 11.230.1 I believe.

**Comment by Shayulghul** [comment]
I'm not sure whether you're on v10, but I read in another thread that reverting to v5.0.6 works in v10. That's what I'm doing until I can update to v11. v5.0.6 is working for me in my v10 games.

**Comment by BBendriss** [comment]
i

> I'm not sure whether you're on v10, but I read in another thread that reverting to v5.0.6 works in v10. That's what I'm doing until I can update to v11. v5.0.6 is working for me in my v10 games.

Hmm. Was on v11, D&D Build 3.2.1
