### ISSUE TITLE
Weight Total for Loot Sheet

### ISSUE THREAD

**Issue by CoryMG** [jopeek/fvtt-loot-sheet-npc-5e#41]
Add a total weight line for contents on sheet so it can be used to track total weight of loot the characters have in containers.

**Comment by TiloBuechsenschuss** [comment]
Second this. Very useful for a bag of holding, for instance.

**Comment by Ikxale** [comment]
third this. very useful for if the party has a wagon or airship or something. would also be great in pf2e

**Comment by jopeek** [comment]
Implemented in 2.5.0
