### ISSUE TITLE
Module not working in DnD5e 2.3.1 with LootSheetNPC 11.231.3

### ISSUE THREAD

**Issue by LuvacZantor** [jopeek/fvtt-loot-sheet-npc-5e#415]
I just installed the module and I do not get the option to pick the "sheet" on an actor. I see there was something similar in August, is it still a thing?  Foundry version 11 Build 315.

**Comment by LuvacZantor** [comment]
It also happens with all other modules off.

**Comment by jopeek** [comment]
Make sure you switch to lootsheet simple. https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/11.231.3

Sent with Spark

**Comment by LuvacZantor** [comment]
unfortunately, i am.

**Comment by LuvacZantor** [comment]
I'm an idiot. I had the wrong actor type..... **NPC** Loot Sheet. Sorry for the bother.
