### ISSUE TITLE
Unable to see player(s)

### ISSUE THREAD

**Issue by Victionator** [jopeek/fvtt-loot-sheet-npc-5e#416]
I am not able to create a lootsheet, that is able to be seen by everyone. There are only a few people that are able to see the the sheet itself.

It has something to do with the permissions, but the thing is, is that I don't see all my registered players. 
If someone would be able to help, that's be great!
![Merchant](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/55739824/f935190c-5538-46c9-99c2-ecbf7c4c5737)

**Comment by jopeek** [comment]
Make sure every player is associated with their character. You do this from the bottom left player list.

**Comment by Victionator** [comment]
![image](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/55739824/e74d95d1-cc11-400a-bf41-ad351fc91889)
If you mean that every player should have their character, I've already done that aswell.

**Comment by jopeek** [comment]
Ok, are you on dnd5e 3 yet or still on 2.4? I can take a look at this sometime soon, I hope.

**Comment by Victionator** [comment]
I'm running Foundry on 2.4

**Comment by nuck1234** [comment]
I have the same issue. I associated the players and nothing is showing in the permissions. I{ have the same issue in innocent loot where the players are not showing.
