### ISSUE TITLE
Cannot edit prices/add items from anywhere but Plutonium

### ISSUE THREAD

**Issue by use643** [jopeek/fvtt-loot-sheet-npc-5e#417]
Cannot edit prices/add manual items to the merchant sheet

To reproduce
Create a new merchant sheet
Import items with and without a set "value" into the merchant sheet
The add button and edit buttons on the merchant sheet do nothing and no console error is spit out

**Expected behavior**
When pressing the edit button, I should be able to set the price of the item I am trying to sell.

**Screenshots**

**Desktop:**
 - Windows
 - Firefox, but issue happens in application
 - 11 stable, build 315

**Additional context**
The item descriptions also do not populate

**Comment by LuvacZantor** [comment]
Same Issues in Chrome.

**Comment by vaka42** [comment]
Same Issues here. Firefox and Chrome.
Foundry Virtual Tabletop - v11.315
Dungeons & Dragons Fifth Edition Game System - v3.0.3

I can't expand the item description in the loot window and can't open the editor window for the items.

**Comment by Alivender** [comment]
Yeah, the buttons to Add, Edit or Delete items in the merchants inventory do not work. You can drag items in from compendiums, but you can do nothing with them afterwards. Shame, it looked like a great module, but it's completely unusable.

**Comment by jopeek** [comment]
Yeah it is a shame. Dnd5e v3 and pretty much every update they make breaks basic functionality. I don’t have time to keep up. One day I probably will. Till then, if anyone wants to contribute a fix, I’d be more than happy to accept it.

**Comment by Xeonis** [comment]
Let`s try to fix, 3.2.0v dnd v5 very different from version 2

**Comment by AskMP** [comment]
Looking at the code, it would seem that there are no event handlers for the edit and delete buttons. The data-action attribute was setup on the list items but no function or event listeners are created. Interestingly, there is a QuantityDialog class setup but it is not associated to the editing, just purchasing or looting.

**Comment by AskMP** [comment]
Just a heads up, I’ve put 2x pull requests with different functionality in them:
- Delete Event Listener, which makes the delete button function as expected
- Edit button event listener, which makes the edit button AND the name open the item screen which allows editing for the owner and viewing the details as a player.
