### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by Marsrc03** [jopeek/fvtt-loot-sheet-npc-5e#418]
**Describe the bug**
Module can't be downloaded due to " Unable to load valid module manifest data " error. 

**To Reproduce**
1. Attempt to install from either github page or foundry module installer
2. See error

**Expected behavior**
I expected to be able to download and use the module

**Screenshots**
<img width="949" alt="error" src="https://github.com/jopeek/fvtt-loot-sheet-npc-5e/assets/164730360/f465322c-e9a5-437f-a55b-92038fbbf851">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome / Foundry
 - Version 11 Build 315

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Marsrc03** [comment]
I see this was a previous issue when it wasn't on version 11 yet, but the[ foundry webpage](https://foundryvtt.com/packages/lootsheetnpc5e/) states that it was made functional with the current built. Is this correct or am I misunderstanding / a separate issue?

**Comment by jopeek** [comment]
It should be partially functional at least… this install issue I wasn’t aware of. I’ll see if I can look into it.

**Comment by Marsrc03** [comment]
I have found that this is an issue on my end. After getting the same issue with other updated modules, I decided to attempt to install foundry and the problem modules on my laptop. My laptop was able to install this module with no issue, as well as other modules I was getting on my desktop. This issue can be closed.
