### ISSUE TITLE
Update to core v.12

### ISSUE THREAD

**Issue by Axberg84** [jopeek/fvtt-loot-sheet-npc-5e#419]
**Is your feature request related to a problem? Please describe.**
Since fvtt got the 12 update this mod dont work.

**Describe the solution you'd like**
Update.

**Describe alternatives you've considered**
looking for alternative but have not found one.

**Comment by Fridan99** [comment]
+1

**Comment by Xeonis** [comment]
First I'm trying to fix the bugs in version 11.315, then I'm trying to update to version 12

**Comment by ChessGH** [comment]
+1, an essential foundry module

**Comment by Fridan99** [comment]
any news? :P

**Comment by jopeek** [comment]
I just installed V12 so I’ll possibly take a look this weekend to see what the damage is :)

**Comment by jopeek** [comment]
Just pushed a new version that should work. Did a bunch of cleanup as well. Probably still has some bugs, but it's likely better than the version you had for v11 :)
