### ISSUE TITLE
Cannot roll on table until the rollable table is changed

### ISSUE THREAD

**Issue by espositos** [jopeek/fvtt-loot-sheet-npc-5e#42]
The rolltable flag is only set when a change is made to the rollable table dropdown, but it should be set when the actor is created or when the sheet is opened for the first time. If you only have one roll table, you are stuck in a position where there is no other table to switch to, which means a change is never triggered and therefore a flag for the rolltable is never set. You will get the 'rolltable is undefined' error forever or until you add another table and switch between them.

**Comment by jopeek** [comment]
Fixed in 2.1.1
