### ISSUE TITLE
D&D 4.0.0 support

### ISSUE THREAD

**Issue by mcmlevi** [jopeek/fvtt-loot-sheet-npc-5e#424]
Hey, I love the module, but I ran into the issue that the module isn't supported after updating the game system to 4.0.0. if this could be updated that would be amazing.

I am unsure if a simple update to the module json is enough in this case.

**Comment by jopeek** [comment]
Hadn’t noticed that 4.0.0 came out yet… if history tells me anything, it’ll be a giant pain to update it, but I’ll take a look later this weekend.

**Comment by jopeek** [comment]
Make that next weekend. I’ve got a game going on and this 4.0.0 update looks too big to want to investigate before that game is done. Patience please :)

**Comment by mcmlevi** [comment]
I feel that, I can imagine it might run into issues in the meantime I suppose I'll see if I can figure out how to downgrade the DND system for now and wait for this.
