### ISSUE TITLE
Bug: Buying container with items leaves items behind on the merchant

### ISSUE THREAD

**Issue by lholden** [jopeek/fvtt-loot-sheet-npc-5e#425]
**Describe the bug**
When you have a container (Explorer's Pack, for example) on the merchant and a player buys it, it them leaves all the items from the container behind on the merchant.

**To Reproduce**
1. Create merchant actor
2. Change merchant's sheet type to Loot Sheet NPC 5e.
3. Drag Explorer's Pack to merchant
4. Buy Explorer's Pack
5. Notice that all the items from the Explorer's Pack got left behind in the Merchant's inventory.

**Expected behavior**
The Actor buying the container to have all the items that were in the container

**Environment:**
Foundry: v12 331
D&D: 4.0.3
Loot Sheet NPC 5e: 12.400.3

**Additional context**

**Comment by jopeek** [comment]
I'm currently working on a significant update, so I will look into this as well.

**Comment by lholden** [comment]
> I'm currently working on a significant update, so I will look into this as well.

Awesome :)

Droplet just got a fix for this and Item Piles has a similar bug. So I'm not surprised loot sheet has an issue around this as well. Seems like a common pain point for mods with the 4.0.X release. :)

**Comment by jopeek** [comment]
FYI, this still persists in the version I'm about to release, but I'll try to make it work in the next update.

**Comment by jopeek** [comment]
Please try version 12.400.5 and give me feedback. In my testing, it seems to work fine. I tested both purchasing and looting of containers with a variety of contents, including currency. Everything comes across.

**Comment by lholden** [comment]
Thanks for the update. It's getting better, but I did notice an issue still.

If you check out the Explorer's Pack from the PHB 2024 module (Just a good example of an container with items) it has a Waterskin that itself has 4 pints of water on it. 

![image](https://github.com/user-attachments/assets/894391c4-1fcc-4247-82b3-a5f40aaf32cb)

If I have an actor and a merchant selling the item
![image](https://github.com/user-attachments/assets/52d839d3-0a9f-4e01-96f3-d7fe634bb534)

And then buy the item. You will notice that the water from the Waterskin gets left behind.
![image](https://github.com/user-attachments/assets/07574714-4f97-495b-bb73-73b7a3e54007)

So in this case... items within a container within a container. :D.

**Comment by jopeek** [comment]
Try 12.400.7. I've attempted to do a recursive copy of containers. There's a caveat... it will not keep the container inside the new container, but rather at the top inventory level. But no contents are lost this way. 

So, if you have a container with three other containers, each with 2 other containers inside them, you'll end up with 1 + 3 + (3*2) containers at the top inventory level.

**Comment by jopeek** [comment]
Going to consider this resolved as best as possible.
