### ISSUE TITLE
Bug: Buying an item from a stack gives you a stack

### ISSUE THREAD

**Issue by lholden** [jopeek/fvtt-loot-sheet-npc-5e#427]
**Describe the bug**
If you buy a single item from a stack, you end up getting a quantity that was the remainder of the stack. So for example. If the merchant has 19 rations on them and you click the "Buy Item" option, you pay for 1 item and get 19. The merchant now has a stack of 18.

I tested this on an empty world with no other modules.

**To Reproduce**
1. Make a Merchant with 20 rations
2. Make a Player with gold
3. On the player, click "Buy Item" on the Rations
4. Player now has a stack of 20 rations, the stack on the merchant is now 19.

**Expected behavior**
To only have the one item :)

**Screenshots**
![image](https://github.com/user-attachments/assets/209f8e65-1cb6-4390-b5f8-421b9cc221fe)

**Environment:**
Foundry: v12 332
D&D: 4.0.3
Loot Sheet NPC 5e: 12.400.5

**Comment by kay1010100** [comment]
Just made the same bug report XD

**Comment by jopeek** [comment]
I’ll get this fixed today. I think I know what I did...

**Comment by kay1010100** [comment]
> I’ll get this fixed today. I think I know what I did...

Thanks for the quick responce

**Comment by jopeek** [comment]
This should be resolved in 12.400.6
