### ISSUE TITLE
Bug: Quantity Bug when buying

### ISSUE THREAD

**Issue by kay1010100** [jopeek/fvtt-loot-sheet-npc-5e#428]
**Describe the bug**
When a player is buying 1 item form a stack of items from the merchant. Then from the merchant sheet 1 item gets removed from the stack, but the player gets the whole stack anyway even though they payed the price for 1

**To Reproduce**
Setup a merchant with a item for sale with a quantity higher than 1
buy one item, you get the whole stack

**Expected behavior**
you get only 1 item instead of the entire stack

**Screenshots**
![Screenshot_2](https://github.com/user-attachments/assets/35598b33-f63a-48d2-a780-f38ac7da0cf7)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser: Chrome
 - Version: Foundry [12.331] - DnD5e Core System [4.0.2] - Loot Sheet NPC [12.400.5]

**Comment by kay1010100** [comment]
This is a duplicate bug report.
https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/427

**Comment by jopeek** [comment]
Will close this and track on the other one.
