### ISSUE TITLE
Currency convert on buy/sell

### ISSUE THREAD

**Issue by TheAtrivion** [jopeek/fvtt-loot-sheet-npc-5e#44]
When I click buy it converts all currency to the highest possible, please make this an option rather than default if possible. Would be very nice if it just drew what it needed from say copper and if the player doesn't have enough copper it takes a silver or two and converts them to copper.

**Comment by ExileofBrokenSky** [comment]
Seconded, I run a world where every price is in gp, since that's the default value used when buying with this mod, and only gp, there is nothing smaller or bigger in my world. I'd love the option to just disable the use of other coin types.

**Comment by dangerdaren** [comment]
Agreed. Having this same issue. Fantastic module outside of that, but yeah--having issues with the current conversion settings.

**Comment by jopeek** [comment]
Addressed in 2.1.0
