### ISSUE TITLE
Currencyt Convertion rate setting

### ISSUE THREAD

**Issue by TheAtrivion** [jopeek/fvtt-loot-sheet-npc-5e#45]
It would be splendid if there was an option for this. The standard Dnd5e is 10cp to 1 silver. But in my world the transfer rate is 100cp to 1 silver. 
This would also mean that the Merchants Price would have to be able to be written 0.001 for 1cp prices, as it is now it defaults to 0 if that's written.
Just a bonus for those of us that have our own currency values =)

**Comment by ktrieun** [comment]
If Loot Sheet used the built in currency rates set in DND5E.currencyConversion in /Data/systems/dnd5e/module/config.js, I wrote a simple module to adjust the conversion rate so that would change the rate.
