### ISSUE TITLE
Handle remainders when splitting

### ISSUE THREAD

**Issue by tonyrobots** [jopeek/fvtt-loot-sheet-npc-5e#46]
Currently if you have 5 coins, and try to split 6 ways (for instance), it will give each person 0, and set the amount remaining to 0. 

It should either distribute what it can, so that in that example a random 5 of the 6 players would get a coin, or, if that's too difficult, it should do what it does now, but leave the remainder in the container to be distributed manually.

**Comment by tonyrobots** [comment]
Just forked the code and will take a stab at this, too! Hope to be able to contribute :)

**Comment by jopeek** [comment]
Love it, thanks :)

**Comment by tonyrobots** [comment]
Done! Very simple, but my players will appreciate not getting shortchanged 😉 
https://github.com/jopeek/fvtt-loot-sheet-npc-5e/pull/47
