### ISSUE TITLE
Quality of life improvements

### ISSUE THREAD

**Issue by pdf** [jopeek/fvtt-loot-sheet-npc-5e#56]
This module is of great utility, but there are a few paper-cuts that would make working with it less laborious for players and DMs:

- [ ] Loot all button: A `Loot All`button to allow a player to simply take all loot, or perhaps checkboxes, with a select-all box at the top, and a `Loot Selected` button would speed up many operations. Applies only for `Type: Loot`.
- [ ] Looting of stacks: Looting an item stack is currently quite laborious, since the correct number has to be entered into the field. For single-quantity stacks this kind of feels even worse, since there can only be one valid answer. Being able to loot a full stack quickly would be very welcome - perhaps shift+click on the loot icon should trigger this, analogous to how rolls work. With this implemented, we could possibly even do without the above feature, since it would speed up looting dramatically, though for long loot lists, Loot All might still be optimal. Maybe applies for both `Type: Loot` and `Type: Merchant`, not 100% certain if this is desirable for merchants.
- [ ] Player controlled currency looting: Allowing players to trigger the gold split (#40 and #39) would be very nice, my preference is for Observer to allow this. I presume that would have to be sent via the GM session to update other player's tokens though. Another button allowing a player to take all currency for their own actor would also be very welcome (not all party members are altruistic :wink:). Applies only for `Type: Loot`.
- [ ] Bulk Permissions: Being able to give all players a specific level of access quickly would be a big boon, especially for larger games.  This can be done ahead-of-time by setting permissions on the actor, but that makes the loot actor visible to players in the actors tab, which is rarely desirable. Applies for both `Type: Loot` and `Type: Merchant`.

**Comment by jopeek** [comment]
Addressed in 2.1.0
