### ISSUE TITLE
 Selling items to the NPC

### ISSUE THREAD

**Issue by LucianoMonsores** [jopeek/fvtt-loot-sheet-npc-5e#59]
It would be of great help if it were possible, for example, for players to sell some items they have in their inventory to the NPC.

- I don't know if it would be possible for Merchant to do both functions (buy and sell), but if it is not possible, should be great to have another option besides Loot and Merchant, just to buy items from players. As GM we would only need to have an NPC to buy (new feature) and another one for sale (merchant).

- A suggestion would be to drag and drop the item into the NPC sheet. After dragging and dropping, a confirmation screen just appears to the player doesn't accidentally sell any item.
- The NPC would buy the item, only if he had enough money
- The price modifier can still be valid to define the percentage of purchase of the item.
- The base value of the item can be collected on the moved item itself (edit the item and see the price value).
- After all, the value of the NPC is discounted and the value is added to the character's sheet (something opposite to what is done for the Merchant).

Thanks in advance,
Luciano

**Comment by franckflo** [comment]
I second this, being able to use the merchants for both buying AND selling in DnD 5e would be wonderful. It seems the PF1 version has that feature, but not the 5e version. Thanks in advance!
