### ISSUE TITLE
Purchasing 1 manually added item removes all regardless of quantity

### ISSUE THREAD

**Issue by dangerdaren** [jopeek/fvtt-loot-sheet-npc-5e#61]
I have a tavern where the inventory is filled via rolltables. But I noticed that if I manually add a new item and set the quantity to say, 10. If a Player clicks the purchase button on that item, a query asks how many he wants to buy. Player chooses 1. 1 of them goes in his inventory (correctly), but the other 9 in the shop vanish instantly (incorrectly).

However, if he chooses to purchase one of the items filled via the rolltable, it works as expected, correctly deducting 1 from that item's quantity without removing all the rest of them.

**Comment by dangerdaren** [comment]
Correction--if the player purchases an item added thru a rolltable it doesn't work as expected after all. Now now matter what quantity the player purchases, he ends up buying the whole stock.

**Comment by feltz916** [comment]
Adding a note here, for devs. This bug seems to only fail when the Loot Sheet is linked to an actor. It works fine when it is not linked.
