### ISSUE TITLE
Increase price modifier upper bound.

### ISSUE THREAD

**Issue by Deniedpluto** [jopeek/fvtt-loot-sheet-npc-5e#65]
Currently upper bound is limited to 2x base price. It would be nice to be able to increase this beyond 2x. Curse of Strahd, for example, has a shop where prices are 10x of PHB.

**Comment by mr-bo-jangles** [comment]
Yeah, I'd suggest getting rid of the slider and making the price multiplier unbounded or stupidly high, like 1,000,000% becasue there is always someone who's going to need a large markup on a store for money sink purposes

**Comment by BlitzKraig** [comment]
#72

**Comment by jopeek** [comment]
Merged in for version 2.2.2

**Comment by BlitzKraig** [comment]
Merged in: 4da68746c28d7c9412bbba2a9b73e093b8670277 , immediately reverted in next commit: 12740aa75f00854dcb97d126e449710c5a802cf4

If the code was buggy or not up to snuff, do you mind if I create a new issue re-requesting the functionality?

**Comment by jopeek** [comment]
I don’t remember tbh if it was because it was buggy or due to some other issue. Let me look at this again.
