### ISSUE TITLE
A NPC created by a player and the sheet changed to a loot sheet becomes unopenable by everyone

### ISSUE THREAD

**Issue by depili** [jopeek/fvtt-loot-sheet-npc-5e#66]
If players are granted the "create actors" permission and then a player creates a new NPC actor, opens it's sheet and changes the sheet of that actor to loot sheet the NPC becomes unopenable by everyone, including the GM. A work-around is to have the GM create the actors and assign permissions.

**Comment by mvanduijvenvoorde** [comment]
I may have the same problem
