### ISSUE TITLE
GM is unable to split coin distribution from loot sheet

### ISSUE THREAD

**Issue by feltz916** [jopeek/fvtt-loot-sheet-npc-5e#67]
**Bug:**
When clicking the Split button on a loot sheet, coinage is not split among the designated actors and an error pops up "No active character for user".

**Notes:**
The flow does work for a player if that player is set to Owner for the loot sheet.
Also note, any modification to the coin manually by the GM generates the same error "No active character for user", but the coin change is accepted.

**Comment by jopeek** [comment]
Fixed in 2.1.2
