### ISSUE TITLE
Spells added to inventory via Rollable Table are not converted to scrolls

### ISSUE THREAD

**Issue by mr-bo-jangles** [jopeek/fvtt-loot-sheet-npc-5e#69]
If I drag and drop the scroll, it's converted correctly and given a price (fairly low though, can we set that as users?)

Loading from my Better Rolltables "Treasure Table" the item isn't converted to a scroll and is instead added as Loot of "True Strike" for example. I will add that the scroll is actually picked three rolltables down, but I don't know if that makes a difference?

**Comment by koganei** [comment]
I'm having the same issue. Even a simple rollable table with spells in it (no multi-level tables) doesn't convert the spells to scrolls.
