### ISSUE TITLE
Ability to deduplicate rolltable added items, just increasing the quantity instead

### ISSUE THREAD

**Issue by mr-bo-jangles** [jopeek/fvtt-loot-sheet-npc-5e#70]
Silly Example
![image](https://user-images.githubusercontent.com/291570/96311640-d802b580-1001-11eb-8919-b4962c5c1ef9.png)

Would be nice if it looked first to see if the item existed and added to quantity? I can see other people wanting different behaviour so probably best to make that a swappable behaviour. 

Dropdown of options like:
Ignore Duplicates - Don't add Items, Don't Add Quantity.
Deduplicate - Don't add Items, Do add to Quantity.
Duplicate - Add Items, Don't add to quantity (original behaviour)

**Comment by jopeek** [comment]
Totally agree but this doesn't seem straightforward to do as every item added gets a unique ID, even if it's the same item.

**Comment by ccjmk** [comment]
could you maybe iterate over the items with a .map, returning the same item with +1 quantity if the names match ? I haven't looked at the code, but it *should* be moderately easy if you have a list of items as I presume, I'll see if I can give it a look later!

**Comment by jopeek** [comment]
Technically yes, though matching by name.... yuck :)

**Comment by ccjmk** [comment]
Well, yes, if you are worried about performance, you could work around something like adding stuff into a binary tree for searching or something, but it honestly sounds a little overkill for what, 50+ items tops?

> Technically yes, though matching by name.... yuck :)
> […](#)
> On Dec 15, 2020, at 3:36 AM, ccjmk ***@***.***> wrote: ﻿ could you maybe iterate over the items with a .map, returning the same item with +1 quantity if the names match ? I haven't looked at the code, but it should be moderately easy if you have a list of items as I presume, I'll see if I can give it a look later! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by benbarbour** [comment]
Yeah, I think matching by name is the right thing to do here. If it's the performance that you're objecting to, I'm the IDs are strings anyway so if you're already checking for duplicates by ID somewhere you're doing string matching (or it's looking them up in a hash, I guess). Also, what @ccjmk said: I don't think it's not enough items to worry about.

**Comment by jopeek** [comment]
This is now default behaviour.
