### ISSUE TITLE
Update to Foundry 0.7.6 and DnD5e 0.99

### ISSUE THREAD

**Issue by jalensailin** [jopeek/fvtt-loot-sheet-npc-5e#74]
Hi there, I know very little about coding but thought I'd give you the heads up that the new versions of Foundry and the DnD5e system are not totally compatible with your new sheets. The icons for inventory items get real long now. Everything else seems to be working but I'm sure I've overlooked some of the features since I'm new to Foundry and this module. Thanks for a wonderful module so far though!

**Comment by jopeek** [comment]
Yep, planning on updating them today depending on if I run into any issues.

**Comment by jalensailin** [comment]
Thanks a ton, you are awesome.

**Comment by DivertedCircle** [comment]
One thing I've noticed, and it may be a module conflict, is that drag and drop to re-order isn't working. Don't know if it's possible, but one quality of life feature I'd love to see when that's fixed would be having the sheet no longer jump to the top any time you move/delete an item.

**Comment by jopeek** [comment]
I’m pretty sure the jump to top is a core “feature” and I hate it, too. I’ll have to test that though.

**Comment by tobloef** [comment]
Should this perhaps be closed, due to https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/2.2.0?

**Comment by jopeek** [comment]
Yes indeed
