### ISSUE TITLE
Drag and Drop Reorder Doesn't Work

### ISSUE THREAD

**Issue by DivertedCircle** [jopeek/fvtt-loot-sheet-npc-5e#75]
Drag and drop to reorder items on a merchant style sheet doesn't seem to work on the latest versions of Foundry.

Foundry v0.7.7
D&D Fifth Edition v1.1.1
Loot Sheet NPC v2.2.0

**Comment by jopeek** [comment]
Enforced alphabetical sorting. That doesn't necessarily do what you're asking for here but I am not sure why drag and reorder doesn't work anymore.

**Comment by jopeek** [comment]
Still enforcing the alphabetical sorting but rows can now be dragged for purposes of dragging items to another sheet, for example.

**Comment by DivertedCircle** [comment]
No chance of drag and drop being readded huh?
