### ISSUE TITLE
Viewing with loot sheet breaks another module's overlay

### ISSUE THREAD

**Issue by Akaito** [jopeek/fvtt-loot-sheet-npc-5e#78]
The module "Virtual Tabletop Assets - Party overview" has an optional tooltip you can use for tokens.  It provides info on HP, AC, speed, and passive checks.  For some reason, merely viewing an actor at any point in its past with loot sheet breaks this other module's overlay forever after.  I'll open the same issue on their module so they're aware, but it's odd that loot sheet is changing something in this way.

The error is:
```
Foundry VTT | Error thrown in hooked function bound onHoverToken foundry.js:2498:15

TypeError: this.getTotalGP(...).toFixed is not a function
    getActorDetails https://((redacted-url))/modules/vtta-party/src/app/index.js:176
    onHoverToken https://((redacted-url))/modules/vtta-party/src/app/index.js:300
    _call https://((redacted-url))/scripts/foundry.js:2496
    callAll https://((redacted-url))/scripts/foundry.js:2456
    _onHoverIn https://((redacted-url))/scripts/foundry.js:11777
    _onHoverIn https://((redacted-url))/scripts/foundry.js:45161
    _onAlt https://((redacted-url))/scripts/foundry.js:2982
    _handleKeys https://((redacted-url))/scripts/foundry.js:2808
    _onKeyDown https://((redacted-url))/scripts/foundry.js:2760
    KeyboardManager https://((redacted-url))/scripts/foundry.js:2636
    initializeKeyboard https://((redacted-url))/scripts/foundry.js:6706
    setupGame https://((redacted-url))/scripts/foundry.js:6555
    _initializeGameView https://((redacted-url))/scripts/foundry.js:7306
    initialize https://((redacted-url))/scripts/foundry.js:6479
    async* https://((redacted-url))/scripts/foundry.js:7436
    async* https://((redacted-url))/scripts/foundry.js:7434
foundry.js:2499:15
```

**Comment by akrigline** [comment]
@Akaito in case this is still an issue for you, the VTTA Party Overview module has not been updated in a while, it's definitely not compatible with the latest version of dnd5e system. For token tooltips, I'd suggest looking at [Token Tooltip Alt](http://github.com/bmarian/token-tooltip-alt) as a replacement. Sadly I don't know of a replacement for the party overview dialog part.

**Comment by Akaito** [comment]
> 
> 
> @Akaito in case this is still an issue for you, the VTTA Party Overview module has not been updated in a while, it's definitely not compatible with the latest version of dnd5e system. For token tooltips, I'd suggest looking at [Token Tooltip Alt](https://github.com/bmarian/token-tooltip-alt) as a replacement. Sadly I don't know of a replacement for the party overview dialog part.

Thanks!  For now I've just:
- Disabled the VTTA tooltip, but kept VTTA for the quick look at languages, passives, etc.
- Configured Combat Utility Belt to give an on-token tooltip with AC, passive perception, and walk speed.
