### ISSUE TITLE
Hide unused categories

### ISSUE THREAD

**Issue by ccjmk** [jopeek/fvtt-loot-sheet-npc-5e#84]
It would be nice if possible, to hide (maybe under a button if for whatever reason you want to enable/disable them, or a config flag on module settings, but just hiding them by default makes sense to me) to hide unused categories on merchants/loots.

So for example, I have a merchant that only sells weapons, no other categories should appear, etc.

**Comment by jopeek** [comment]
Implemented in 2.4.2
