### ISSUE TITLE
Alternate currency schema causes render fails after programmatic sheet change

### ISSUE THREAD

**Issue by unsoluble** [jopeek/fvtt-loot-sheet-npc-5e#86]
Appears as if LootSheet is converting the currency schema on actors when it's enabled for the first time, and then expects the currency schema to be in this format for subsequent sheet renders.

Unfortunately this leads to render failures if the actor's sheet is instead changed programmatically, as LootSheet attempts and fails to parse the "standard" currency schema:

![image](https://user-images.githubusercontent.com/801582/103387965-8b386200-4abb-11eb-8d28-11c68ea64cd3.png)

I'm afraid I'm not entirely sure what the best fix for this would be, aside from if at all possible not changing away from the standard schema. Or perhaps doing a check for its state before render and converting anew if necessary?

**Comment by unsoluble** [comment]
What appears to be happening is that "fresh" 5e 1.2.0 actors have this for `_token.actor.data.data.currency`:
![image](https://user-images.githubusercontent.com/801582/103388293-1d8d3580-4abd-11eb-899d-37a7f9d2d484.png)

Which changes to this format after LS has been rendered once for the actor:
![image](https://user-images.githubusercontent.com/801582/103388280-08180b80-4abd-11eb-8e3a-b40b0798fe3c.png)

**Comment by jopeek** [comment]
Feels like the proper fix here is for me to ensure lootsheet's coin structure follows that of the new dnd5e standard.

**Comment by unsoluble** [comment]
Currently hacking around this by manually converting actors to the schema LS is expecting, like so:

```js
if (typeof(token.actor.data.data.currency.cp) === "number") {
    let newCurrencyData = {};
    newCurrencyData['data.currency'] = {
        'cp': {'value': token.actor.data.data.currency.cp},
        'ep': {'value': token.actor.data.data.currency.ep},
        'gp': {'value': token.actor.data.data.currency.gp},
        'pp': {'value': token.actor.data.data.currency.pp},
        'sp': {'value': token.actor.data.data.currency.sp}
    };
    await token.actor.update(newCurrencyData);
}
```
...which was working for me for a while, but inexplicably has stopped — I'm now getting `User [Player] lacks permission to update Tokens in parent` on the player end when opening sheets for looping, if I use this migration on a token.

How's progress on supporting the new 5e schema? :D

**Comment by schultzcole** [comment]
I haven't gone through the code with a fine-toothed comb, but it seems like a big issue here is that when the currency structure is incorrect, it tries to update the token to match the currency structure it expects. And if the first person to open the sheet is a player, you run into problems because the player doesn't have permission to update the token.

In addition to changing the currency structure, I would suggest that any conversion that needs to be done should *not* be done by the sheet when it is rendered, but should rather be done when the sheet is changed to be the loot sheet with something like so:

```js
Hooks.on("preUpdateToken", (scene, token, delta, options, user) => {
    if (delta.actorData?.flags?.core?.sheetClass === "dnd5e.LootSheet5eNPC") {
        // we know that this update corresponds with the sheet type changing to loot sheet npc
        // we can add on additional changes by mutating the `delta` object:
        if (!delta.actorData.data) delta.actorData.data = {};
        delta.actorData.data.currency = {
            cp: { value: 1 },
            ep: { value: 2 },
            gp: { value: 3 },
            pp: { value: 4 },
            sp: { value: 5 },
        };
    }
});
```
