### ISSUE TITLE
Can't put modifier in merchant roll

### ISSUE THREAD

**Issue by benbarbour** [jopeek/fvtt-loot-sheet-npc-5e#89]
In either of the "Formula" fields in the Merchant settings, rolls with modifiers are not evaluated correctly. The effects of these seem slight different depending on the field in question.

For the "Shop Qty Formula" field, if you enter something like "3d4+4" then click the "Update Shop Inventory" button, nothing happens. Nothing is even logged. This is because on this [this line](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/5319a91fd2064a972d665951e7c139bf09e56ed8/lootsheetnpc5e.js#L236) `shopQtyRoll.result` is a string containing the evaluated roll plus the modifier (e.g. "6 +4"), and `i < "6+4"` is evaluating false, skipping the loop entirely.

For the "Item Qty Formula" the modifier just ends up in the quantifier field of the newly added item (see screenshot). 

![image](https://user-images.githubusercontent.com/487715/103507238-8bb25f00-4e13-11eb-94fb-620c3bff85f7.png)

**Comment by jopeek** [comment]
Fixed in 2.4.0
