### ISSUE TITLE
Entries are wider since V1.6 update?

### ISSUE THREAD

**Issue by Sekierer** [jopeek/fvtt-loot-sheet-npc-5e#9]
I assume the latest update where you added the $ sign to make purchases available to players screwed a bit with column width or something, so each entry is wider than it should be?

![image](https://user-images.githubusercontent.com/64690637/80867487-991bb600-8c94-11ea-811a-e7576881f5c3.png)

**Comment by jopeek** [comment]
This looks to be caused by another mod adding an additional icon in that last column. favetab maybe? If you can confirm the module, I can reproduce it and just the styling to allow for the additional icon to appear without wrapping to a second line.

**Comment by Sekierer** [comment]
Yes It's Favourite Item Tab, you are right^^
