### ISSUE TITLE
Prevent Duplicates settings is backwards

### ISSUE THREAD

**Issue by benbarbour** [jopeek/fvtt-loot-sheet-npc-5e#90]
If you check "prevent duplicates", it sets a variable called `allowDups` to `true`, and AFAICT from reading the code and playing with the sheet for a few minutes, turning on "prevent duplicates" actually does allow duplicates.

https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/bb62f7da5ae7cab8746d77ea4d1209a3429faf8a/template/npc-sheet.html#L102

**Comment by jopeek** [comment]
I think you’re right. I noticed this last weekend during my game. I’ll try to remember to fix this.

**Comment by jopeek** [comment]
Fixed in 2.4.0
