### ISSUE TITLE
Infinite loop if "Prevent Duplicates" is unset and table is exhausted.

### ISSUE THREAD

**Issue by benbarbour** [jopeek/fvtt-loot-sheet-npc-5e#91]
If you make a table with 2 items, then set the "Shop Qty Formula" to 3d4 so that the minimum draw is 3 items, and don't allow duplicates (but see #90) then pressing the "Update Shop Inventory" button causes an infinite loop, freezing Foundry entirely.

**Comment by jopeek** [comment]
Fixed in 2.4.0
