### ISSUE TITLE
Feature Suggestion: fine tuned/rollable prices

### ISSUE THREAD

**Issue by Ikxale** [jopeek/fvtt-loot-sheet-npc-5e#93]
it would be really cool to be able to have custom prices or modifiers for different items, such as if a town exports lumber cheaply but imports steel for a high price. it'd be useful for anyone doing a game with things like trade goods. 
it would also be amazing if you were able to set it to use a base price+ a dice roll, and reroll the sheet on command by the GM, allowing for minor or major price fluctuations with relative ease

**Comment by Streyder** [comment]
You could just create an item with the correct gold value set?
