### ISSUE TITLE
Feature Suggestion: simple options to allow indirect compatibility with modules that change currency value

### ISSUE THREAD

**Issue by Ikxale** [jopeek/fvtt-loot-sheet-npc-5e#94]
Adding compatibility with other modules which change the currency values, such as 5e custom currency, would be an excellent addition. 
Due to the fact universal compatibility would probably require a decent amount of effort, an easy solution would be to add a toggle in the module settings menu, where if it is enabled, it allows you to change the default piece abbreviation (so instead of GP it could be SP, or even something different entirely like $) as well as change the per coin values.

i looked into the .js file, and while i lack the skills to work with foundry's API and make my own modifications, i was able to change the hardcoded values, which seemingly functioned to the same effect

my proposition would likely be done by adding 5 variables which can be modified in the module settings tab, one for each currency's value, and a string for the text which appears beside the coin value in vendor tables. if i am not mistaken, all it would take to implement would be to change the hardcoded values to use these five variables, and set the default value for the variables as the values they would be by default

**Comment by jopeek** [comment]
Sounds like a reasonable and easily implemented suggestion. I’ll try to add it next time I’m working on it.

**Comment by Ikxale** [comment]
awesome. good luck with it, hopefully there's no oversight or other issue i missed in my reading through the code.

**Comment by Streyder** [comment]
Also relevant for: https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/126 and https://github.com/jopeek/fvtt-loot-sheet-npc-5e/pull/106

**Comment by cstby** [comment]
Sorry to comment on a closed issue. It looks like these values are no longer hard-coded and are pulled from the actor sheet itself? Is that correct? If so, would it follow that there's no way to support custom currencies by changing the code in this module? It would need to be changed on the actor sheet or at the system level?
