### ISSUE TITLE
Looted items do not transfer to player inventory.

### ISSUE THREAD

**Issue by Kailan7401** [jopeek/fvtt-loot-sheet-npc-5e#97]
This is the same issue as https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/76 , which states "Player can loot the item, the looting appears on chat but the item dissapears and is not added to the player inventory." I am using LootSheet 2.5.1 and Foundry 0.7.9, 5e Ruleset 1.2.2, and no other mods.

Of note is that newly created campaigns in 0.7.9 do not have any issues, but the problem is present in a previous campaign that I created in 0.6.6 and LootSheet 2.1.X. If it would be helpful, I can upload the campaign in question.

(I'm not super familiar with github so I wasn't sure if I should create a new issue or attach it to the existing closed one. Apologies if I submitted the report incorrectly)

**Comment by Kailan7401** [comment]
Updated potential workaround: Creating a new character DOES allow the looting functionality to work properly in my old campaign, but characters existed before the campaign, etc. were updated are apparently broken. Duplicating old characters does not fix the functionality.

**Comment by jopeek** [comment]
I’m also using an old campaign like you and it seems to work for my players there. Does it happen on newly created lootsheet characters too?

**Comment by jopeek** [comment]
I see yeah the sheet data structured changes at some point. You’ll have to create new characters from scratch I’m affairs.

**Comment by Streyder** [comment]
This seems to be fixed?
