### ISSUE TITLE
[Request] Custom Buy from Resources

### ISSUE THREAD

**Issue by kunxin-chor** [jopeek/fvtt-loot-sheet-npc-5e#98]
Is it possible to have an option where players can buy items with a resource (or two) from their character sheet? The use case is: I come up with a buy point system for magic items in 5E, and will like them to choose and pick from a Shopkeeper NPC.

**Comment by Streyder** [comment]
I think a custom character genaration resource is well outside the scope of this module. Maybe you can handle this with a "points" to gold conversion somehow?
